<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ShipV1\Dto;

use ShipStream\FedEx\Dto;

final class Address extends Dto
{
    /**
     * @param  ?string[]  $streetLines  Combination of number, street name, etc. At least one line is required for a valid physical address. Empty lines should not be included.98 Royal Crescent
     * @param  ?string  $city  The name of city, town of the recipient.Example: Birmingham
     * @param  ?string  $stateOrProvinceCode  It is used to identify the principal subdivisions (e.g., provinces or states) of countries. The Format and presence of this field may vary depending on the country. Example: CA.<a onclick='loadDocReference("canadaprovincecodes")'>click here to see State or Province Code</a>
     * @param  ?string  $postalCode  The US State and Canada Province codes. The Format and presence of this field may vary depending on the country. Example: 35209<a onclick='loadDocReference("postalawarecountries")'>click here to see Postal aware countries</a>
     * @param  ?string  $countryCode  The two-letter code used to identify a country.Example: US<a onclick='loadDocReference("countrycodes")'>click here to see Country codes</a>
     * @param  ?bool  $residential  Indicate whether this address is residential (as opposed to commercial).Valid Values: True or False.
     */
    public function __construct(
        public ?array $streetLines = null,
        public ?string $city = null,
        public ?string $stateOrProvinceCode = null,
        public ?string $postalCode = null,
        public ?string $countryCode = null,
        public ?bool $residential = null,
    ) {}
}
