<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ShipV1\Dto;

use ShipStream\FedEx\Dto;

final class Alert3pp extends Dto
{
    /**
     * @param  ?string  $code  Specifies the api alert code.<br>Example: RECIPIENTCONTACT.PHONENUMBER.NOTSUPPORTED
     * @param  ?string  $message  Convenient Delivery Options will not be provided with recipient’s landline number. Moving forward, please provide valid mobile phone number.
     */
    public function __construct(
        public ?string $code = null,
        public ?string $message = null,
    ) {}
}
