<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ShipV1\Dto;

use ShipStream\FedEx\Dto;

final class ContentRecord extends Dto
{
    /**
     * @param  ?string  $itemNumber  This is a package item number.
     * @param  ?int  $receivedQuantity  This is the package item quantity.
     * @param  ?string  $description  This is the description of the package item.
     * @param  ?string  $partNumber  This is the part number.
     */
    public function __construct(
        public ?string $itemNumber = null,
        public ?int $receivedQuantity = null,
        public ?string $description = null,
        public ?string $partNumber = null,
    ) {}
}
