<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ShipV1\Dto;

use ShipStream\FedEx\Dto;

final class ContactAndAddressVerify extends Dto
{
    /**
     * @param  ?ContactVerify  $contact  Indicate the contact details of the shipper.
     * @param  ?Address  $address  Address of the manufacturer
     */
    public function __construct(
        public ?ContactVerify $contact = null,
        public ?Address $address = null,
    ) {}
}
