<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ShipV1\Dto;

use ShipStream\FedEx\Dto;

final class CreateShipmentRating extends Dto
{
    protected static array $complexArrayTypes = ['shipmentRateDetails' => ShipmentRateDetail::class];

    /**
     * @param  ?string  $actualRateType  This rate type identifies which entry in the following array is considered as presenting the "actual" rates for the shipment.<br>Example: PAYOR_LIST_SHIPMENT
     * @param  ShipmentRateDetail[]|null  $shipmentRateDetails  Each element of this field provides shipment-level rate totals for a specific rate type.
     * @param  ?Money2  $totalNetTransportationAndPickupCharge  This is commodity value used for Customs declaration.
     * @param  ?Money2  $totalNetFedExTransportationAndPickupCharge  This is commodity value used for Customs declaration.
     * @param  ?PickupRateDetail  $pickupRateDetail  Charges associated with a scheduled shipment pickup
     */
    public function __construct(
        public ?string $actualRateType = null,
        public ?array $shipmentRateDetails = null,
        public ?Money2 $totalNetTransportationAndPickupCharge = null,
        public ?Money2 $totalNetFedExTransportationAndPickupCharge = null,
        public ?PickupRateDetail $pickupRateDetail = null,
    ) {}
}
