<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ShipV1\Dto;

use ShipStream\FedEx\Dto;

final class CreateTagOutputVo extends Dto
{
    protected static array $complexArrayTypes = ['alerts' => Alert::class];

    /**
     * @param  ?string  $masterTrackingNumber  Specifies the Master Tracking Number for the requested shipment.<br>Example: 997338100007320
     * @param  ?string  $serviceType  Specifies the service type for this shipment.<br>Example: GROUND_HOME_DELIVERY<br><a onclick='loadDocReference("servicetypes")'>Click here to see Service Types</a>
     * @param  ?string  $shipTimestamp  Specifies the shipment date and time. The default timestamp is the current date-time. Format is MMM-dd-yyyy.<br>Example: 2019-10-04
     * @param  Alert[]|null  $alerts  Specifies the alerts received when a tag is created. This includes the alert code, alert type, and alert message.
     */
    public function __construct(
        public ?string $masterTrackingNumber = null,
        public ?string $serviceType = null,
        public ?string $shipTimestamp = null,
        public ?CompletedTagDetail $completedTagDetail = null,
        public ?array $alerts = null,
    ) {}
}
