<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ShipV1\Dto;

use ShipStream\FedEx\Dto;

final class DisclaimMessageSet extends Dto
{
    /**
     * @param  ?string  $disclaimCode  Code representing a specific declaration or filing condition.<br>Maximum length is 1.<br> Accepted values<br> 1. A - Product is not regulated by CPSC (meaning no rule, ban, standard, or regulation requiring a certificate applies.)<br> 2. B - Data is not required per CPSC guidance (enforcement discretion)<br>Example: A
     * @param  ?string  $intendedUseCode  Standardized code describing the intended consumer use of the product.<br>Maximum length is 16.<br> Example: 245.001
     * @param  ?string  $intendedUseDescription  Plain-language description of the product’s intended use.<br>Maximum length is 22.<br> Example: Children’s plastic educational toy for ages 3+
     */
    public function __construct(
        public ?string $disclaimCode = null,
        public ?string $intendedUseCode = null,
        public ?string $intendedUseDescription = null,
    ) {}
}
