<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ShipV1\Dto;

use ShipStream\FedEx\Dto;

final class PackageCodDetail extends Dto
{
    /**
     * @param  ?Money  $codCollectionAmount  This customs value is applicable for all items(or units) under the specified commodity
     */
    public function __construct(
        public ?Money $codCollectionAmount = null,
    ) {}
}
