<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ShipV1\Dto;

use ShipStream\FedEx\Dto;

final class ReturnAssociationDetail extends Dto
{
    /**
     * @param  string  $trackingNumber  This is the tracking number associated with this package.<br>Example: 49XXX0000XXX20032835
     * @param  ?string  $shipDatestamp  This is the ship date for the outbound shipment associated with a return shipment. The format is YYYY-MM-DD.<br> Example: 2019-10-01
     */
    public function __construct(
        public readonly string $trackingNumber,
        public readonly ?string $shipDatestamp = null,
    ) {
    }
}
