<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ShipV1\Dto;

use ShipStream\FedEx\Dto;

final class ShipmentDryIceDetail2 extends Dto
{
    /**
     * @param  int  $packageCount  Specifies the package Count for the shipment<br>Example: 10
     * @param  ?Weight  $totalWeight  These are the package weight details.<br>Note: Weight is not required for One rate shipments
     * @param  ?ShipmentDryIceProcessingOptionsRequested  $processingOptions  Specify that dry ice information is only applicable at the shipment level. Package level dry ice information would not apply.
     */
    public function __construct(
        public int $packageCount,
        public ?Weight $totalWeight = null,
        public ?ShipmentDryIceProcessingOptionsRequested $processingOptions = null,
    ) {}
}
