<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ShipV1\Dto;

use ShipStream\FedEx\Dto;

final class SmartPostInfoDetail extends Dto
{
    /**
     * @param  string  $hubId  Required<br>Specify the HubID using the four-digit numeric value.<br>Example: 5015
     * @param  string  $indicia  Specify the indicia type.<br>Available options include:<ul><li>MEDIA_MAIL</li><li>PARCEL_SELECT (1 LB through 70 LB)</li><li>PRESORTED_BOUND_PRINTED_MATTER</li><li>PRESORTED_STANDARD (less than 1 LB)</li><li>PARCEL_RETURN</li></ul>Example:PRESORTED_STANDARD
     * @param  ?string  $ancillaryEndorsement  Required for Presorted Standard but not for returns or parcel select. They are not all usable for all ancillary endorsements.<br>Example: RETURN_SERVICE
     * @param  ?string  $specialServices  SmartPost Shipment Special Service Type<br>Example: USPS_DELIVERY_CONFIRMATION
     */
    public function __construct(
        public string $hubId,
        public string $indicia,
        public ?string $ancillaryEndorsement = null,
        public ?string $specialServices = null,
    ) {}
}
