<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\LocationsSearchV1\Dto;

use ShipStream\FedEx\Dto;

final class Location extends Dto
{
    /**
     * @param  Address  $address  Specifies the Address Details for a location.
     * @param  ?GeoCode  $longLat  The ISO6709 geographic coordinates for a specific geographic location, specifically latitude and longitude.
     */
    public function __construct(
        public Address $address,
        public ?GeoCode $longLat = null,
    ) {}
}
