<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\TrackV1\Dto;

use ShipStream\FedEx\Dto;

final class LocationDetail extends Dto
{
    /**
     * @param  ContactAndAddress  $locationContactAndAddress  Location Contact And Address.
     * @param  ?string  $locationId  Location Identification for facilities identified by an alpha numeric location code. Passing Location Id of the Hold at Location (HAL) address is strongly recommended to ensure packages are delivered to the correct address.<br> Example: SEA
     * @param  ?string  $locationType  The FedEx Location Type.<br> Example: PICKUP_LOCTION
     */
    public function __construct(
        public ContactAndAddress $locationContactAndAddress,
        public ?string $locationId = null,
        public ?string $locationType = null,
    ) {}
}
