<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\TrackV1\Dto;

use ShipStream\FedEx\Dto;

final class ReturnDetail extends Dto
{
    protected static array $complexArrayTypes = ['reasonDetail' => ReasonDetail::class];

    /**
     * @param  ?string  $authorizationName  Name of person authorizing the return, entered by the customer.
     * @param  ReasonDetail[]|null  $reasonDetail  Specifies the return reason details.
     */
    public function __construct(
        public ?string $authorizationName = null,
        public ?array $reasonDetail = null,
    ) {}
}
