<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\OpenShipV1\Dto;

use ShipStream\FedEx\Dto;

final class FullSchemaCreateOpenShipment extends Dto
{
    /**
     * @param  OpenshipmentRequestedShipment  $requestedShipment  The detailed transaction data for the requested Open Shipment.
     * @param  PartyAccountNumber  $accountNumber  This is FedEx Account number details.
     * @param  ?string  $openShipmentAction  Indicates the optional actions that can be performed during the modification of packages in  Open Shipment.<p>Here are the values:<ul><li>CREATE_PACKAGE - Use CREATE_PACKAGE option to create Open Shipment.</li><li>STRONG_VALIDATION – Full shipment edits: any edit that fails will cause the transaction to fail. If the transaction is successful, a tracking number may be returned and the transaction will be saved to the database (committed).</li><li>WEAK_VALIDATION - Full shipment edits: any edit that fails will return errors but the transaction does not fail. The tracking number is returned and the transaction is saved in the database if the core edits are passed. Fix errors with the ModifyRequests transaction using the Index and returned tracking number.</li></ul></p>
     * @param  ?string  $index  This is a unique value assigned to the already created Open Shipment. If this isn’t available then provide the master tracking number.<br>Note: If index is not provided while create open shipment then the master tracking id of create open ship will act as index for the shipment.<br>Example: Test1234
     */
    public function __construct(
        public OpenshipmentRequestedShipment $requestedShipment,
        public PartyAccountNumber $accountNumber,
        public ?string $openShipmentAction = null,
        public ?string $index = null,
    ) {}
}
