<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\OpenShipV1\Dto;

use ShipStream\FedEx\Dto;

final class InternationalTrafficInArmsRegulationsDetail extends Dto
{
    /**
     * @param  string  $licenseOrExemptionNumber  The export or license number for the ITAR shipment.<br>Minimum length is 5 characters.<br>Maximum length is 21 characters.<br>Example: 9871234
     */
    public function __construct(
        public string $licenseOrExemptionNumber,
    ) {}
}
