<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\OpenShipV1\Dto;

use ShipStream\FedEx\Dto;

final class PhoneNumber extends Dto
{
    /**
     * @param  ?string  $areaCode  Indicate the area code for the phone number.
     * @param  ?string  $localNumber  Indicate the local phone number for contacting in the event of an emergency. Maximum length  is 10.
     * @param  ?string  $extension  Indicate the extension for the phone number.
     * @param  ?string  $personalIdentificationNumber  Indicate the Personal Identification Number associated with the phone number.
     */
    public function __construct(
        public ?string $areaCode = null,
        public ?string $localNumber = null,
        public ?string $extension = null,
        public ?string $personalIdentificationNumber = null,
    ) {}
}
