<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\OpenShipV1\Dto;

use ShipStream\FedEx\Dto;

final class ShipShipmentEmailNotificationRecipient extends Dto
{
    /**
     * @param  string  $emailNotificationRecipientType  Specify the recipient type for email notification.
     * @param  string  $emailAddress  Specify the recipient email address.<br>Example: xyz@aol.com
     * @param  ?string  $name  Specify the recipient name.<br>Example: Joe Smith
     * @param  ?string  $notificationFormatType  This is the format for the email notification. Either HTML or plain text can be provided.<br>Example: TEXT
     * @param  ?string  $notificationType  Indicate the type of notification that will be sent as an email<br>Example: EMAIL
     * @param  ?string  $locale  These are the locale details for email.<br>Example: en_US, fr_CA, es_MX,.etc.<br><a onclick='loadDocReference("locales")'>click here to see Locales</a><br>Note: If the locale is left blank or an invalid locale is entered, an error message is returned in response.
     * @param  ?string[]  $notificationEventType  These are to specify the notification event types.<br> Example: [ON_PICKUP_DRIVER_ARRIVED, ON_SHIPMENT]<br><a onclick='loadDocReference("notificationeventtypes")'>Click here for more information on Notification Event Types.</a>
     */
    public function __construct(
        public string $emailNotificationRecipientType,
        public string $emailAddress,
        public ?string $name = null,
        public ?string $notificationFormatType = null,
        public ?string $notificationType = null,
        public ?string $locale = null,
        public ?array $notificationEventType = null,
    ) {}
}
