<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\FreightLTLV1\Dto;

use ShipStream\FedEx\Dto;

final class CompletedHazardousShipmentDetail extends Dto
{
    /**
     * @param  ?CompletedHazardousSummaryDetail  $hazardousSummaryDetail  Specifies Completed Hazardous Summary Detail.
     * @param  ?AdrLicenseDetail  $adrLicense  Specifies the details around the ADR license required for shipping.
     * @param  ?ShipmentDryIceDetail  $dryIceDetail  Specifies the shipment level totals of dry ice data across all packages.
     */
    public function __construct(
        public ?CompletedHazardousSummaryDetail $hazardousSummaryDetail = null,
        public ?AdrLicenseDetail $adrLicense = null,
        public ?ShipmentDryIceDetail $dryIceDetail = null,
    ) {}
}
