<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\FreightLTLV1\Dto;

use ShipStream\FedEx\Dto;

final class CreatePickupOutputVo extends Dto
{
    protected static array $complexArrayTypes = ['alerts' => Alert::class];

    /**
     * @param  ?string  $pickupConfirmationCode  The confirmation number provided to the customer when a freight pickup is requested. <br> Example : XXXX101XXOS45XXXX
     * @param  Alert[]|null  $alerts  These are optional alerts received when a Create freight pickup is requested. This includes an alert code, type, and message.
     */
    public function __construct(
        public ?string $pickupConfirmationCode = null,
        public ?array $alerts = null,
    ) {}
}
