<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\FreightLTLV1\Dto;

use ShipStream\FedEx\Dto;

final class CustomerImageUsage extends Dto
{
    /**
     * @param  ?string  $id  Specify the Image ID.
     * @param  ?string  $type  Specify document image type.
     * @param  ?string  $providedImageType  Specify the provided document image type.
     */
    public function __construct(
        public ?string $id = null,
        public ?string $type = null,
        public ?string $providedImageType = null,
    ) {}
}
