<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\FreightLTLV1\Dto;

use ShipStream\FedEx\Dto;

final class EMailNotificationDetail extends Dto
{
    protected static array $complexArrayTypes = ['emailNotificationRecipients' => EmailNotificationRecipient::class];

    /**
     * @param  ?string  $aggregationType  Indicate the shipment notification aggregation type.
     * @param  EmailNotificationRecipient[]|null  $emailNotificationRecipients  These are email notification recipient details.
     * @param  ?string  $personalMessage  This is your personal message for the email.<br><br>Note: The maximum personal message character limit depends on the element emailNotificationDetail\emailNotificationRecipients\notificationFormatType values:<ul><li>If notificationFormatType is TEXT, then only 120 characters printed on the email</li><li>If notificationFormatType is HTML, then 500 characters printed on the email</li></ul><br>Example: This is concerning the order 123456 of 26 July 2021 - art no 34324-23 Teddy Bear, brown
     */
    public function __construct(
        public ?string $aggregationType = null,
        public ?array $emailNotificationRecipients = null,
        public ?string $personalMessage = null,
    ) {}
}
