<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\FreightLTLV1\Dto;

use ShipStream\FedEx\Dto;

final class FreightGuaranteeDetail extends Dto
{
    /**
     * @param  string  $freightGuaranteeType  Specify how the freight has been guaranteed for delivery.
     * @param  string  $guaranteeTimestamp  Specify the time of shipment based on shippers time zone.<br>Example: 2009-04-12
     */
    public function __construct(
        public string $freightGuaranteeType,
        public string $guaranteeTimestamp,
    ) {}
}
