<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\FreightLTLV1\Dto;

use ShipStream\FedEx\Dto;

final class RateDiscount extends Dto
{
    /**
     * @param  ?float  $amount  Indicates the amount for the rate discount.
     * @param  ?string  $name  Indicate the name of the discount.<br><a onclick='loadDocReference("discounts")'>Click here to see Discounts</a>
     * @param  ?string  $description  Indicates the description for the rate discount.
     * @param  ?string  $type  Indicates the type.
     * @param  ?float  $percent  Indicates the percentage of the rate discount.
     */
    public function __construct(
        public ?float $amount = null,
        public ?string $name = null,
        public ?string $description = null,
        public ?string $type = null,
        public ?float $percent = null,
    ) {}
}
