<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\FreightLTLV1\Dto;

use ShipStream\FedEx\Dto;

final class ShippingDocumentFormat extends Dto
{
    protected static array $complexArrayTypes = ['dispositions' => ShippingDocumentDispositionDetail::class];

    /**
     * @param  ?bool  $provideInstructions  Indicates whether or not to provide the instructions.
     * @param  ?DocumentFormatOptionsRequested  $optionsRequested  Indicate the requested options for document format.
     * @param  ?string  $stockType  Indicate the used label stock type. Note to list the correct type of paper for the freight address label option.
     * @param  ShippingDocumentDispositionDetail[]|null  $dispositions  Specifies how to create, organize, and return the document
     * @param  ?string  $locale  These are locale details.<br>example: 'en_US'<br><a onclick='loadDocReference("locales")'>click here to see Locales</a><br>Note: If the locale is left blank or an invalid locale is entered, an error message is returned in response.
     * @param  ?string  $docType  Specify the image format used for a shipping document.<br><a onclick='loadDocReference("labelstocktypes")'>click here to see label format types</a>
     */
    public function __construct(
        public ?bool $provideInstructions = null,
        public ?DocumentFormatOptionsRequested $optionsRequested = null,
        public ?string $stockType = null,
        public ?array $dispositions = null,
        public ?string $locale = null,
        public ?string $docType = null,
    ) {}
}
