<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\FreightLTLV1\Dto;

use ShipStream\FedEx\Dto;

final class ShipmentSpecialServicesRequestedFreightDirectDetail extends Dto
{
    protected static array $complexArrayTypes = ['freightDirectDataDetails' => FreightDirectDataDetail::class];

    /**
     * @param  FreightDirectDataDetail[]|null  $freightDirectDataDetails
     */
    public function __construct(
        public readonly ?array $freightDirectDataDetails = null,
    ) {
    }
}
