<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\FreightLTLV1\Dto;

use ShipStream\FedEx\Dto;

final class TimeRange extends Dto
{
    /**
     * @param  ?string  $begins  Specifies the start time.
     * @param  ?string  $ends  Specifies the end time.
     */
    public function __construct(
        public ?string $begins = null,
        public ?string $ends = null,
    ) {}
}
