<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\FreightLTLV1\Dto;

use ShipStream\FedEx\Dto;

final class UsmcaDetail extends Dto
{
    /**
     * @param  ?string  $originCriterion  Specify the origin criterion.
     */
    public function __construct(
        public readonly ?string $originCriterion = null,
    ) {
    }
}
