<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\GlobalTradeV1\Dto;

use ShipStream\FedEx\Dto;

final class CommodityComplianceTypeDetail extends Dto
{
    /**
     * @param  float[]|null  $commodityIndexes  This is an array of nonnegative-Integer identifying the associated commodities.
     */
    public function __construct(
        public ?array $commodityIndexes = null,
        public ?RegulatoryComplianceTypeDetail $regulatoryComplianceTypeDetail = null,
    ) {}
}
