<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\GlobalTradeV1\Dto;

use ShipStream\FedEx\Dto;

final class CommercialInvoice extends Dto
{
    /**
     * @param  ?Money  $freightCharge  Specify Insurance charges if applicable.<br><i>Note: FedEx does not provide insurance of any kind</i>.
     * @param  ?string  $purpose  It describes the purpose.
     */
    public function __construct(
        public ?Money $freightCharge = null,
        public ?string $purpose = null,
    ) {}
}
