<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\GlobalTradeV1\Dto;

use ShipStream\FedEx\Dto;

final class LocalizedAttributeDetail extends Dto
{
    /**
     * @param  ?Localization  $localization  Specify locale details for composing email with the document.
     * @param  ?string  $name  Specifies the name of the product being shipped.
     * @param  ?string  $description  Specifies elabaorate material description and other technical details of the product beingshipped.
     */
    public function __construct(
        public ?Localization $localization = null,
        public ?string $name = null,
        public ?string $description = null,
    ) {}
}
