<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\RatesAndTransitTimesV1\Dto;

use ShipStream\FedEx\Dto;

final class CommercialInvoice extends Dto
{
    /**
     * @param  ?string  $shipmentPurpose  The reason for the shipment.  Note: SOLD is not a valid purpose for a Proforma Invoice.
     */
    public function __construct(
        public ?string $shipmentPurpose = null,
    ) {}
}
