<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\RatesAndTransitTimesV1\Dto;

use ShipStream\FedEx\Dto;

final class DateDetail extends Dto
{
    /**
     * @param  ?string  $dayOfWeek  specific day of week in short format<br>Example: MON, TUE
     * @param  ?string  $dayFormat  This is expected delivery date in format [YYYY-MM-DDTHH:mm:ss]<br>Example: 2020-07-16T10:30:00
     */
    public function __construct(
        public ?string $dayOfWeek = null,
        public ?string $dayFormat = null,
    ) {}
}
