<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\RatesAndTransitTimesV1\Dto;

use ShipStream\FedEx\Dto;

final class HazardousCommodityDescription extends Dto
{
    /**
     * @param  ?int  $sequenceNumber  In conjunction with the regulatory identifier, this field uniquely identifies a specific hazardous materials commodity.
     * @param  ?string[]  $processingOptions  Indicates any special processing options to be applied to the description of the dangerous goods commodity.
     * @param  ?string[]  $subsidiaryClasses  Specifies the hazardous material subsidiary classes.
     * @param  ?string  $labelText  Specifies the DOT diamond hazard label type. This element can also include limited quantity or exemption number.
     * @param  ?string  $technicalName  Specify the technical name for the hazardous commodity.
     * @param  ?HazardousCommodityPackingDetail  $packingDetails  Specifies documentation and limits for validation of an individual packing group/category.
     * @param  ?string  $authorization  Information related to quantity limitations and operator or state variations as may be applicable to the dangerous goods commodity.
     * @param  ?bool  $reportableQuantity  The element specifies the reportable quantity of the hazardous material.
     * @param  ?float  $percentage  Indicates the percentage.
     * @param  ?string  $id  Specifies the ID of label text.
     * @param  ?string  $packingGroup  Identifies IATA packing group for a hazardous commodity.
     * @param  ?string  $properShippingName  The proper shipping name as defined by the regulation.<br>The name can also include qualifying words.
     * @param  ?string  $hazardClass  Specify hazard class for commodity.
     */
    public function __construct(
        public ?int $sequenceNumber = null,
        public ?array $processingOptions = null,
        public ?array $subsidiaryClasses = null,
        public ?string $labelText = null,
        public ?string $technicalName = null,
        public ?HazardousCommodityPackingDetail $packingDetails = null,
        public ?string $authorization = null,
        public ?bool $reportableQuantity = null,
        public ?float $percentage = null,
        public ?string $id = null,
        public ?string $packingGroup = null,
        public ?string $properShippingName = null,
        public ?string $hazardClass = null,
    ) {}
}
