<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\RatesAndTransitTimesV1\Dto;

use ShipStream\FedEx\Dto;

final class PickupDetail extends Dto
{
    /**
     * @param  ?\DateTimeInterface  $readyDateTime  Pickup ready date in YYYY-MM-DD format
     * @param  ?\DateTimeInterface  $latestPickupDateTime  Latest pickup date in YYYY-MM-DD format
     * @param  ?string  $courierInstructions  Special instructions for the courier
     * @param  ?string  $requestType  Type of pickup request
     * @param  ?string  $requestSource  Source of the pickup request
     */
    public function __construct(
        public ?\DateTimeInterface $readyDateTime = null,
        public ?\DateTimeInterface $latestPickupDateTime = null,
        public ?string $courierInstructions = null,
        public ?string $requestType = null,
        public ?string $requestSource = null,
    ) {}
}
