<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\RatesAndTransitTimesV1\Dto;

use ShipStream\FedEx\Dto;

final class PickupRateDetail extends Dto
{
    protected static array $complexArrayTypes = [
        'freightDiscounts' => RateDiscount::class,
        'rebates' => Rebate::class,
        'surcharges' => Surcharge::class,
        'taxes' => Tax::class,
        'dutiesAndTaxes' => EdtCommodityTax::class,
        'ancillaryFeesAndTaxes' => AncillaryFeeAndTax::class,
    ];

    /**
     * @param  ?string  $rateType  Type used for this specific set of rate data.
     * @param  ?string  $rateScale  Indicates the rate scale used.
     * @param  ?string  $rateZone  Indicates the rate zone used (based on origin and destination).
     * @param  ?string  $ratingBasis  Allows clients to determine whether to add charges at the package level when Per Piece Rating details are returned.<br><ul><li>SHIPMENT_WEIGHT_BASED - Indicates shipment weight is used to calculate the rate.</li><br><li>FLAT_RATE_PER_PAK - Indicates shipment is rated based on number of packs, weight would be considered for overweight surcharge but not for calculating shipment rate.</li><br><li>PACK_WEIGHT_BASED - Indicates individual package weight would be rated and aggregated to get shipment rate weight.</li></ul>
     * @param  ?string  $pricingCode  Identifies the type of pricing used for this shipment.
     * @param  ?string  $minimumChargeType  provides the minimum charge type applicable to the rates.
     * @param  ?CurrencyExchangeRate  $currencyExchangeRate  Specifies the currency exchange performed on financial amounts for this rate.
     * @param  ?string[]  $specialRatingApplied  Indicates which special rating cases applied to this shipment.
     * @param  ?float  $fuelSurchargePercent  Specify a fuel surcharge percentage.
     * @param  ?string  $pickupBaseChargeDescription  Will indicate the pickup charge description of the on call pickup
     * @param  ?TotalBaseCharge  $totalBaseCharge  Total base charges for the shipment.
     * @param  ?TotalFreightDiscounts  $totalFreightDiscounts  The total discounts used in the rate calculation.<br> Example: 1257.26
     * @param  ?TotalNetFreight  $totalNetFreight  This shipment's totalNetFreight.
     * @param  ?TotalSurcharges  $totalSurcharges  The sum of all surcharges on the package.
     * @param  ?TotalNetFedExCharge  $totalNetFedExCharge  This shipment's totalNetFedExCharge, which is totalNetFreight plus totalSurcharges (not including totalTaxes).
     * @param  ?TotalTaxes  $totalTaxes  The sum of all taxes on this package.<br> Example: 1257.25
     * @param  ?TotalNetCharge  $totalNetCharge  Total net charges for the shipment.
     * @param  ?TotalRebates  $totalRebates  The total sum of all rebates applied to this package.
     * @param  ?TotalDutiesAndTaxes  $totalDutiesAndTaxes  The sum of shipment/package Duties and taxes.
     * @param  ?TotalAncillaryFeesAndTaxes  $totalAncillaryFeesAndTaxes  Identifies the shipment-level fees and taxes that are not based on transportation charges or commodity-level estimated duties and taxes.
     * @param  ?TotalDutiesTaxesAndFees  $totalDutiesTaxesAndFees  The total amount of the duties and taxes plus the total ancillary fees and taxes.
     * @param  ?TotalNetChargeWithDutiesAndTaxes  $totalNetChargeWithDutiesAndTaxes  Total netChargesWithDutiesAndTaxes for the shipment.
     * @param  RateDiscount[]|null  $freightDiscounts  All rate discounts that apply to this shipment
     * @param  Rebate[]|null  $rebates  The all rebates applied to this package.
     * @param  Surcharge[]|null  $surcharges  The amount of surcharges applied to this shipment.
     * @param  Tax[]|null  $taxes  List of taxes.
     * @param  EdtCommodityTax[]|null  $dutiesAndTaxes  List of The shipment/package Duties and taxes.
     * @param  AncillaryFeeAndTax[]|null  $ancillaryFeesAndTaxes  Identifies the total amount of the shipment-lvel fees and taxes that are not based on transportation charges of commodity-level estimated duties and taxes.
     * @param  ?VariableHandlingCharges  $variableHandlingCharges  Optional. The variable handling charge amount calculated based on the requested variable handling charge detail.
     * @param  ?TotalVariableHandlingCharges  $totalVariableHandlingCharges  Optional. The variable handling charge amount calculated based on the requested variable handling charge detail.
     */
    public function __construct(
        public ?string $rateType = null,
        public ?string $rateScale = null,
        public ?string $rateZone = null,
        public ?string $ratingBasis = null,
        public ?string $pricingCode = null,
        public ?string $minimumChargeType = null,
        public ?CurrencyExchangeRate $currencyExchangeRate = null,
        public ?array $specialRatingApplied = null,
        public ?float $fuelSurchargePercent = null,
        public ?string $pickupBaseChargeDescription = null,
        public ?TotalBaseCharge $totalBaseCharge = null,
        public ?TotalFreightDiscounts $totalFreightDiscounts = null,
        public ?TotalNetFreight $totalNetFreight = null,
        public ?TotalSurcharges $totalSurcharges = null,
        public ?TotalNetFedExCharge $totalNetFedExCharge = null,
        public ?TotalTaxes $totalTaxes = null,
        public ?TotalNetCharge $totalNetCharge = null,
        public ?TotalRebates $totalRebates = null,
        public ?TotalDutiesAndTaxes $totalDutiesAndTaxes = null,
        public ?TotalAncillaryFeesAndTaxes $totalAncillaryFeesAndTaxes = null,
        public ?TotalDutiesTaxesAndFees $totalDutiesTaxesAndFees = null,
        public ?TotalNetChargeWithDutiesAndTaxes $totalNetChargeWithDutiesAndTaxes = null,
        public ?array $freightDiscounts = null,
        public ?array $rebates = null,
        public ?array $surcharges = null,
        public ?array $taxes = null,
        public ?array $dutiesAndTaxes = null,
        public ?array $ancillaryFeesAndTaxes = null,
        public ?VariableHandlingCharges $variableHandlingCharges = null,
        public ?TotalVariableHandlingCharges $totalVariableHandlingCharges = null,
    ) {}
}
