<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\RatesAndTransitTimesV1\Dto;

use ShipStream\FedEx\Dto;

final class ProductName extends Dto
{
    /**
     * @param  ?string  $type  Specifies the type of the product.<br> Example: medium
     * @param  ?string  $encoding  Specifies the encoding standard. <br> Example: utf-8.
     * @param  ?string  $value  Specifies the value of the Product.<br> Example: FedEx International First®.
     */
    public function __construct(
        public ?string $type = null,
        public ?string $encoding = null,
        public ?string $value = null,
    ) {}
}
