<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\RatesAndTransitTimesV1\Dto;

use ShipStream\FedEx\Dto;

final class Surcharge extends Dto
{
    /**
     * @param  ?string  $surchargeType  The type of surcharge.
     * @param  ?string  $level  The level of surcharge.
     * @param  ?string  $description  The description of the surcharge.
     * @param  ?Money  $amount  Indicate the amount details. This is optional, but if indicated, amount and currency must be provided.
     */
    public function __construct(
        public ?string $surchargeType = null,
        public ?string $level = null,
        public ?string $description = null,
        public ?Money $amount = null,
    ) {}
}
