<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ServiceAvailabilityV1\Dto;

use ShipStream\FedEx\Dto;

final class CodeDisplayTextVo extends Dto
{
    /**
     * @param  ?string  $displayText  Display Text
     * @param  ?string  $code  Unique code
     */
    public function __construct(
        public ?string $displayText = null,
        public ?string $code = null,
    ) {}
}
