<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ServiceAvailabilityV1\Dto;

use ShipStream\FedEx\Dto;

final class CommitDetailTransitDays extends Dto
{
    /**
     * @param  ?string  $description  Specifies the number of days the package/shipment is to be in transit.
     * @param  ?string  $minimumTransitTime  This is a code indicating the number of transit days available.
     */
    public function __construct(
        public ?string $description = null,
        public ?string $minimumTransitTime = null,
        public ?string $maximumTransitTime = null,
    ) {}
}
