<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ServiceAvailabilityV1\Dto;

use ShipStream\FedEx\Dto;

final class TransitTimeRequestedShipmentCustomsClearanceDetail extends Dto
{
    protected static array $complexArrayTypes = ['commodities' => TransitTimeCommodity::class];

    /**
     * @param  TransitTimeCommodity[]  $commodities  Specify the commodity details.
     */
    public function __construct(
        public array $commodities,
    ) {}
}
