<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ServiceAvailabilityV1\Dto;

use ShipStream\FedEx\Dto;

final class TransitTimeDetail extends Dto
{
    protected static array $complexArrayTypes = ['customerMessages' => CustomerMessage::class];

    /**
     * @param  ?string  $serviceType  Type of the service is returned.
     * @param  CustomerMessage[]|null  $customerMessages  These are messages returned in the response.
     * @param  ?Distance  $distance  This is a total distance between origin and destination city centers for freight shipments.
     * @param  ?CommitDetail  $commit  The delivery commitment details.
     * @param  ?string  $serviceName  Name of service returned.
     */
    public function __construct(
        public ?string $serviceType = null,
        public ?array $customerMessages = null,
        public ?Distance $distance = null,
        public ?CommitDetail $commit = null,
        public ?LocationDetail $destinationLocation = null,
        public ?string $serviceName = null,
    ) {}
}
