<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ServiceAvailabilityV1\Dto;

use ShipStream\FedEx\Dto;

final class TransitTimeRequestedShipmentShipmentSpecialServices extends Dto
{
    /**
     * @param  ?string[]  $specialServiceTypes  Indicate special services for which the rate data is being requested. Special Services are available at the shipment level for some or all service types.<br>Example: BROKER_SELECT_OPTION <br><a onclick='loadDocReference("shipmentlevelspecialservicetypes")'>Click here to see Shipment level Special Service Types</a>
     * @param  ?TransitTimeRequestedShipmentShipmentSpecialServicesCodDetail  $codDetail  Use this object to specify Collect On Delivery (COD) shipment details.
     * @param  ?TransitTimeRequestedShipmentShipmentSpecialServicesInternationalControlledExportDetail  $internationalControlledExportDetail  Use this object to specify International Controlled Export shipment Details.
     * @param  ?TransitTimeRequestedShipmentShipmentSpecialServicesHomeDeliveryPremiumDetail  $homeDeliveryPremiumDetail  These are Special service elements for FedEx Ground Home Delivery shipments. If selected, element homedeliveryPremiumType is mandatory.
     * @param  ?TransitTimeRequestedShipmentShipmentSpecialServicesHoldAtLocationDetail  $holdAtLocationDetail  Use this object to specify required information of a shipment to be held at FedEx destination location. <br><br><i>Note: This object HoldAtLocationDetail is <b>REQUIRED</b>, when HOLD_AT_LOCATION is chosen in the specialServiceTypes.</i>
     * @param  ?TransitTimeRequestedShipmentShipmentSpecialServicesShipmentDryIceDetail  $shipmentDryIceDetail  Use this object to indicate package count with weight for this shipment containing dry ice. Dry ice is supported in both shipment level and package level services.
     */
    public function __construct(
        public ?array $specialServiceTypes = null,
        public ?TransitTimeRequestedShipmentShipmentSpecialServicesCodDetail $codDetail = null,
        public ?TransitTimeRequestedShipmentShipmentSpecialServicesInternationalControlledExportDetail $internationalControlledExportDetail = null,
        public ?TransitTimeRequestedShipmentShipmentSpecialServicesHomeDeliveryPremiumDetail $homeDeliveryPremiumDetail = null,
        public ?TransitTimeRequestedShipmentShipmentSpecialServicesHoldAtLocationDetail $holdAtLocationDetail = null,
        public ?TransitTimeRequestedShipmentShipmentSpecialServicesShipmentDryIceDetail $shipmentDryIceDetail = null,
    ) {}
}
