<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: ShipStream\FedEx\Generator\Generators\RequestGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ShipDGHazmatV1\Requests;

use Exception;
use Saloon\Contracts\Body\HasBody;
use Saloon\Enums\Method;
use Saloon\Http\Response;
use Saloon\Traits\Body\HasJsonBody;
use ShipStream\FedEx\Api\ShipDGHazmatV1\Dto\FullSchemaShipShipment;
use ShipStream\FedEx\Api\ShipDGHazmatV1\Responses\ErrorResponseVo;
use ShipStream\FedEx\Api\ShipDGHazmatV1\Responses\ShpcResponseVo;
use ShipStream\FedEx\Request;

/**
 * DGHazShipment
 *
 * This endpoint helps you to create shipment requests thereby validating all the shipping input
 * information and either generates the labels (if the responses is synchronous) or a job ID if
 * transaction is processed using asynchronous method.<br><i>Note: FedEx APIs do not support
 * Cross-Origin Resource Sharing (CORS) mechanism.<i>
 */
class DgHazShipment extends Request implements HasBody
{
    use HasJsonBody;

    protected Method $method = Method::POST;

    /**
     * @param  FullSchemaShipShipment  $fullSchemaShipShipment  The request elements required to create a shipment.
     */
    public function __construct(
        public FullSchemaShipShipment $fullSchemaShipShipment,
    ) {}

    public function resolveEndpoint(): string
    {
        return '/ship/v1/dghazshipments';
    }

    public function createDtoFromResponse(Response $response): ShpcResponseVo|ErrorResponseVo
    {
        $status = $response->status();
        $responseCls = match ($status) {
            200 => ShpcResponseVo::class,
            400, 401, 403, 404, 500, 503, 429 => ErrorResponseVo::class,
            default => throw new Exception("Unhandled response status: {$status}")
        };

        return $responseCls::deserialize($response->json());
    }

    public function defaultBody(): array
    {
        return $this->fullSchemaShipShipment->toArray();
    }
}
