<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\AccountRegistrationV1\Dto;

use ShipStream\FedEx\Dto;

final class AddressVo extends Dto
{
    /**
     * @param  bool  $residential  Indicates whether this address is residential (as opposed to commercial).
     * @param  string  $city  Specify name of city or town.
     * @param  string  $countryCode  The two-letter code used to identify a country. Max length is 2.<br><a onclick='loadDocReference("countrycodes")'>Click here to see Country Codes</a>
     * @param  string  $postalCode  Use this element to input postal code. Postal code is mandatory for postal-aware countries. The Max length is 10.<br><a onclick='loadDocReference("postalawarecountries")'>Click here to see Postal Codes</a>
     * @param  string[]  $streetLines  Provide street address which is a combination of number, street name, etc. At least one line is required. For a valid physical address, empty lines should not be included. Max Length is 35.
     * @param  string  $stateOrProvinceCode  Provide 2 letter state or province code. Not used for Ground/SmartPost. Max length is 2.<br><a onclick='loadDocReference("canadaprovincecodes")'>Click here to see State or Province Codes</a>
     */
    public function __construct(
        public bool $residential,
        public string $city,
        public string $countryCode,
        public string $postalCode,
        public array $streetLines,
        public string $stateOrProvinceCode,
    ) {}
}
