<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\AccountRegistrationV1\Dto;

use ShipStream\FedEx\Dto;

final class BaseProcessOutputVo extends Dto
{
    protected static array $attributeMap = ['childKey' => 'child_Key', 'childSecret' => 'child_secret'];

    protected static array $complexArrayTypes = ['mfaOptions' => MfaOptionsInner::class];

    /**
     * @param  MfaOptionsInner[]|null  $mfaOptions  It provide options to generate the secure pin or validate invoice
     * @param  ?string  $childKey  Child Key is a JSON Web Token provided for each of your customers. You must use the Child Key along with the Client Key, Client Secret and Customer Secret to get oAuth token, which should be used as credentials with each API transaction.
     * @param  ?string  $childSecret  Child secret, also referred to as <i>Customer Secret</i>, is provided for each of your customers. You must use the Customer Secret along with the Client Key, Client Secret and Child Key to get the oAuth token, which should be used as credentials with each API transaction.
     */
    public function __construct(
        public ?array $mfaOptions = null,
        public ?string $childKey = null,
        public ?string $childSecret = null,
    ) {}
}
