<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\AccountRegistrationV1\Dto;

use ShipStream\FedEx\Dto;

final class IssuePinInputVo extends Dto
{
    /**
     * @param  string  $option  Indicates option selected by the user to send generated pin.
     * @param  ?string  $locale  Indicates the user locale.<br><a onclick='loadDocReference("locales")'>click here to see locales</a>
     */
    public function __construct(
        public string $option,
        public ?string $locale = null,
    ) {}
}
