<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\AccountRegistrationV1\Dto;

use ShipStream\FedEx\Dto;

final class ValidateInvoiceInputVo extends Dto
{
    /**
     * @param  InvoiceDetails  $invoiceDetail  This field indicates and Object holds Invoice Details.
     * @param  ?string  $locale  Indicates locale and will be used for locale if x-locale is missed from header.<br><a onclick='loadDocReference("locales")'>Click here to see Locales</a>
     */
    public function __construct(
        public InvoiceDetails $invoiceDetail,
        public ?string $locale = null,
    ) {}
}
