<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ConsolidationV1\Dto;

use ShipStream\FedEx\Dto;

final class AssociatedTrackingDetails extends Dto
{
    protected static array $complexArrayTypes = ['trackingIds' => TrackingIds::class];

    /**
     * @param  TrackingIds[]|null  $trackingIds  Tracking details for the package to be retrieved from the Open shipment.
     * @param  ?string  $type  Provides the type of associated tracking details.<br> Example: CONSOLIDATION_MASTER
     */
    public function __construct(
        public readonly ?array $trackingIds = null,
        public readonly ?string $type = null,
    ) {
    }
}
