<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ConsolidationV1\Dto;

use ShipStream\FedEx\Dto;

final class BrokerDetail extends Dto
{
    /**
     * @param  ?Party3  $broker
     * @param  ?string  $type  Identifies the type of Broker.
     */
    public function __construct(
        public readonly ?Party3 $broker = null,
        public readonly ?string $type = null,
    ) {
    }
}
