<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ConsolidationV1\Dto;

use ShipStream\FedEx\Dto;

final class ConsolidationDocumentSpec extends Dto
{
    protected static array $complexArrayTypes = ['customDocumentDetails' => Formats::class];

    /**
     * @param  ?string[]  $consolidationDocumentTypes  Specifies consolidation document types.
     * @param  ?ConsolidationDocumentSpec1ConsolidatedCommercialInvoiceDetail  $consolidatedCommercialInvoiceDetail  Specifies consolidated commercial invoice detail.
     * @param  ?ConsolidationDocumentSpec1CustomsPackingListDetail  $customsPackingListDetail  Specifies the customs packing list detail.
     * @param  ?ConsolidationDocumentSpec1CrnReportDetail  $crnReportDetail  Specifies the child reference number report detail.
     * @param  ?ConsolidationDocumentSpec1CondensedCrnReportDetail  $condensedCrnReportDetail  Specifies the child reference number report detail for condensed CrnReport Detail.
     * @param  ?ConsolidationDocumentSpec1ConsolidatedCustomsLinehaulReportDetail  $consolidatedCustomsLinehaulReportDetail  Specifies the child reference number report detail for consolidated customs linehaul report detail.
     * @param  ?ConsolidationDocumentSpec1ConsolidatedPartyReportDetail  $consolidatedPartyReportDetail  Specifies the child reference number report detail for consolidated party report detail.
     * @param  ?ConsolidationDocumentSpec1ConsolidatedSoldToSummaryReportDetail  $consolidatedSoldToSummaryReportDetail  Specifies the child reference number report detail for consolidated SoldTo summary report detail.
     * @param  ?ConsolidationDocumentSpec1ConsolidatedSoldToSummaryReportDetail  $commoditiesByTrackingNumberDetail  Specifies the child reference number report detail for consolidated SoldTo summary report detail.
     * @param  Formats[]|null  $customDocumentDetails  Specifies the child reference number report detail for consolidated SoldTo summary report detail.
     */
    public function __construct(
        public ?array $consolidationDocumentTypes = null,
        public ?ConsolidationDocumentSpec1ConsolidatedCommercialInvoiceDetail $consolidatedCommercialInvoiceDetail = null,
        public ?ConsolidationDocumentSpec1CustomsPackingListDetail $customsPackingListDetail = null,
        public ?ConsolidationDocumentSpec1CrnReportDetail $crnReportDetail = null,
        public ?ConsolidationDocumentSpec1CondensedCrnReportDetail $condensedCrnReportDetail = null,
        public ?ConsolidationDocumentSpec1ConsolidatedCustomsLinehaulReportDetail $consolidatedCustomsLinehaulReportDetail = null,
        public ?ConsolidationDocumentSpec1ConsolidatedPartyReportDetail $consolidatedPartyReportDetail = null,
        public ?ConsolidationDocumentSpec1ConsolidatedSoldToSummaryReportDetail $consolidatedSoldToSummaryReportDetail = null,
        public ?ConsolidationDocumentSpec1ConsolidatedSoldToSummaryReportDetail $commoditiesByTrackingNumberDetail = null,
        public ?array $customDocumentDetails = null,
    ) {}
}
