<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ConsolidationV1\Dto;

use ShipStream\FedEx\Dto;

final class ConsolidationCompletedShipmentDetail extends Dto
{
    protected static array $complexArrayTypes = ['completedPackageDetails' => CompletedPackageDetail::class];

    /**
     * @param  CompletedPackageDetail[]|null  $completedPackageDetails
     * @param  ?ShipmentOperationalDetail  $operationalDetail  Shipment level operational information.
     * @param  ?string  $carrierCode  Specify the four letter code of a FedEx operating company that meets your requirements<br>Examples of FedEx Operating Companies are:<ul><li>FDXE - FedEx Express</li><li>FDXG - FedEx Ground</li><li>FXSP - FedEx SmartPost</li><li>FXCC - FedEx Custom Critical.</li></ul>
     * @param  ?CompletedHoldAtLocationDetail  $completedHoldAtLocationDetail  Returns the default holding location information when HOLD_AT_LOCATION special service is requested and the client does not specify the hold location address.
     * @param  ?CompletedEtdDetail  $completedEtdDetail  These are completed ETD details when ELECTRONIC_TRADE_DOCUMENTS Special service type is requested
     * @param  ?string  $packagingDescription  Specifies packaging description.
     * @param  ?TrackingId  $masterTrackingId  The field is present to allow use of preassigned Master Airway Bill tracking number.
     * @param  ?ServiceDescription  $serviceDescription  Provides Service Description.
     * @param  ?bool  $usDomestic  Indicates whether or not this is an intra-U.S. shipment.
     * @param  ?CompletedHazardousShipmentDetail  $hazardousShipmentDetail  Completed shipment level hazardous commodity information.
     * @param  ?ShipmentRating  $shipmentRating  All shipment-level rating data for this shipment, which may include data for multiple rate types.
     * @param  ?DocumentRequirementsDetail  $documentRequirements  Provides the document requirements detail.
     * @param  ?string  $exportComplianceStatement  Specifies export Compliance Statement.
     * @param  ?PendingShipmentAccessDetail  $accessDetail  This information describes how and when a online email return label shipment may be accessed for completion.
     * @param  ?ShipmentConsolidationDetail  $shipmentConsolidationDetail  Provides the shipment consolidation details.
     * @param  ?CompletedCodDetail  $completedCodDetail  Provides the complete collection detail.
     */
    public function __construct(
        public ?array $completedPackageDetails = null,
        public ?ShipmentOperationalDetail $operationalDetail = null,
        public ?string $carrierCode = null,
        public ?CompletedHoldAtLocationDetail $completedHoldAtLocationDetail = null,
        public ?CompletedEtdDetail $completedEtdDetail = null,
        public ?string $packagingDescription = null,
        public ?TrackingId $masterTrackingId = null,
        public ?ServiceDescription $serviceDescription = null,
        public ?bool $usDomestic = null,
        public ?CompletedHazardousShipmentDetail $hazardousShipmentDetail = null,
        public ?ShipmentRating $shipmentRating = null,
        public ?DocumentRequirementsDetail $documentRequirements = null,
        public ?string $exportComplianceStatement = null,
        public ?PendingShipmentAccessDetail $accessDetail = null,
        public ?ShipmentConsolidationDetail $shipmentConsolidationDetail = null,
        public ?CompletedCodDetail $completedCodDetail = null,
    ) {}
}
