<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ConsolidationV1\Dto;

use ShipStream\FedEx\Dto;

final class ConsolidationShipmentsConsolidationRequestedShipmentsCompletedShipmentDetailDocumentRequirements extends Dto
{
    /**
     * @param  ?string  $requiredDocuments  Indicates the required documents information.<br>Example: ["COMMERCIAL_OR_PRO_FORMA_INVOICE","AIR_WAYBILL"]
     * @param  ?ConsolidationShipmentsConsolidationRequestedShipmentsCompletedShipmentDetailDocumentRequirementsGenerationDetails  $generationDetails  Specifies the generation details.
     */
    public function __construct(
        public readonly ?string $requiredDocuments = null,
        public readonly ?ConsolidationShipmentsConsolidationRequestedShipmentsCompletedShipmentDetailDocumentRequirementsGenerationDetails $generationDetails = null,
    ) {
    }
}
