<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ConsolidationV1\Dto;

use ShipStream\FedEx\Dto;

final class ConsolidationShipmentsConsolidationRequestedShipmentsConsolidationDetailInternationalDistribtuionDetailSummaryDetail extends Dto
{
    /**
     * @param  ?ConsolidationShipmentsConsolidationRequestedShipmentsConsolidationDetailInternationalDistribtuionDetailSummaryDetailTotalWeight  $totalWeight
     * @param  ?int  $totalPackageCount  non-negative number
     * @param  ?int  $totalUniqueAddressCount  non-negative number
     * @param  ?ConsolidationShipmentsConsolidationRequestedShipmentsConsolidationDetailInternationalDistribtuionDetailSummaryDetailTotalCustomsValue  $totalCustomsValue
     */
    public function __construct(
        public readonly ?ConsolidationShipmentsConsolidationRequestedShipmentsConsolidationDetailInternationalDistribtuionDetailSummaryDetailTotalWeight $totalWeight = null,
        public readonly ?int $totalPackageCount = null,
        public readonly ?int $totalUniqueAddressCount = null,
        public readonly ?ConsolidationShipmentsConsolidationRequestedShipmentsConsolidationDetailInternationalDistribtuionDetailSummaryDetailTotalCustomsValue $totalCustomsValue = null,
    ) {
    }
}
