<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ConsolidationV1\Dto;

use ShipStream\FedEx\Dto;

final class ConsolidationShipmentsConsolidationRequestedShipmentsLabelSpecification extends Dto
{
    /**
     * @param  ?string  $labelFormatType  Specify the label Format Type.<br><a onclick='loadDocReference("labelstocktypes")'>click here to see label format types</a>
     * @param  ?string  $labelStockType  Indicate the label stock type used. <br><a onclick='loadDocReference("labelstocktypes")'>click here to see label format types</a>
     * @param  ?string  $imageType  Specify the image format used for a shipping document.<br><a onclick='loadDocReference("labelstocktypes")'>click here to see label format types</a>
     * @param  ?string  $labelPrintingOrientation  This is applicable only to documents produced on thermal printers with roll stock.
     */
    public function __construct(
        public readonly ?string $labelFormatType = null,
        public readonly ?string $labelStockType = null,
        public readonly ?string $imageType = null,
        public readonly ?string $labelPrintingOrientation = null,
    ) {
    }
}
