<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ConsolidationV1\Dto;

use ShipStream\FedEx\Dto;

final class ConsolidationShipmentsConsolidationRequestedShipmentsRequestedPackageLineItemsTrackingId extends Dto
{
    /**
     * @param  ?string  $trackindIdType  Indicates the tracking details of the package.
     * @param  ?string  $formId  This is FedEx tracking Identifier associated with the package.<br>Example: 8600
     * @param  ?string  $trackingNumber  This is the number associated with the package that is used to track it. <br>Example: 49XXX0000XXX20032835
     */
    public function __construct(
        public readonly ?string $trackindIdType = null,
        public readonly ?string $formId = null,
        public readonly ?string $trackingNumber = null,
    ) {
    }
}
