<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ConsolidationV1\Dto;

use ShipStream\FedEx\Dto;

final class ConsolidationShipmentsConsolidationRequestedShipmentsConsolidationDetail extends Dto
{
    /**
     * @param  ?TransborderDistributionDetail  $transborderDistributionDetail  Specifies attributes of a shipment whithin a transborder distribution.
     */
    public function __construct(
        public ?string $relationshipTimeStamp = null,
        public ?string $type = null,
        public ?string $role = null,
        public ?ConsolidationShipmentsConsolidationRequestedShipmentsConsolidationDetailInternationalDistribtuionDetail $internationalDistribtuionDetail = null,
        public ?TransborderDistributionDetail $transborderDistributionDetail = null,
    ) {}
}
