<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ConsolidationV1\Dto;

use ShipStream\FedEx\Dto;

final class ConsolidationShipmentsConsolidationRequestedShipmentsConsolidationDetailInternationalDistribtuionDetailSummaryDetail extends Dto
{
    /**
     * @param  ?int  $totalPackageCount  non-negative number
     * @param  ?int  $totalUniqueAddressCount  non-negative number
     */
    public function __construct(
        public ?ConsolidationShipmentsConsolidationRequestedShipmentsConsolidationDetailInternationalDistribtuionDetailSummaryDetailTotalWeight $totalWeight = null,
        public ?int $totalPackageCount = null,
        public ?int $totalUniqueAddressCount = null,
        public ?ConsolidationShipmentsConsolidationRequestedShipmentsConsolidationDetailInternationalDistribtuionDetailSummaryDetailTotalCustomsValue $totalCustomsValue = null,
    ) {}
}
