<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ConsolidationV1\Dto;

use ShipStream\FedEx\Dto;

final class ContactAndAddress extends Dto
{
    /**
     * @param  ?Contact  $contact  Contact details for the Party such as Name, Email, PhoneNumber.
     * @param  ?ContactAncillaryDetail  $contactAncillaryDetail  Indicates additional contact details for the Party such as email and phone contact information.
     * @param  ?Address  $address  Descriptive data for a physical location. May be used as an actual physical address (place to which one could go), or as a container of "address parts" which should be handled as a unit (such as a city-state-ZIP combination within the US).
     * @param  ?AddressAncillaryDetail  $addressAncillaryDetail  Indicates additional address details for the physical location.
     */
    public function __construct(
        public readonly ?Contact $contact = null,
        public readonly ?ContactAncillaryDetail $contactAncillaryDetail = null,
        public readonly ?Address $address = null,
        public readonly ?AddressAncillaryDetail $addressAncillaryDetail = null,
    ) {
    }
}
