<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ConsolidationV1\Dto;

use ShipStream\FedEx\Dto;

final class CreateConsolidationOutputVo extends Dto
{
    protected static array $complexArrayTypes = ['trackingIds' => TrackingIds::class, 'alerts' => Alert::class];

    /**
     * @param  TrackingIds[]|null  $trackingIds  The field is present to allow use of preassigned Master Airway Bill tracking number.
     * @param  ?ConsolidationKey  $consolidationKey  Identifies the consolidation to which this open shipment should be added after successful creation.
     * @param  Alert[]|null  $alerts  The alerts received when processing a shipment request.
     */
    public function __construct(
        public ?array $trackingIds = null,
        public ?ConsolidationKey $consolidationKey = null,
        public ?array $alerts = null,
    ) {}
}
