<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ConsolidationV1\Dto;

use ShipStream\FedEx\Dto;

final class CustomsClearanceDetailCommercialInvoice extends Dto
{
    /**
     * @param  ?string  $termsOfSale  Specify terms Of Sale that will be populated on the Commercial Invoice (or Pro Forma). Maximum length is 3.<br>Valid values are:<ul><li>FCA/FOB (Free Carrier/Free On Board): Seller is responsible for all costs of delivering goods to destination. (Default)</li><li>CIP (Costs, Insurance Paid): Seller is responsible for miscellaneous charges to destination.</li><li>CPT (Carriage Paid To): Buyer is responsible for insurance.</li><li>EXW (Ex Works): Seller makes goods available to buyer. Buyer is responsible for delivering goods to destination.</li><li>DDU (Delivered Duty Unpaid): Seller is responsible for delivering goods to destination. Buyer is responsible for clearing goods through Bureau of Customs and Border Protection.</li><li>DDP (Delivered Duty Paid): Seller is responsible for delivering goods to destination, including duties, taxes, and miscellaneous fees.</li><li>DAP (Delivered at Place): Seller pays for carriage to the named place except for costs related to import clearance, and assumes all risks prior to the point that the goods are ready for unloading by the buyer.</li><li>DPU (Deliver at Place of Unloading)</li></ul>
     * @param  ?string[]  $comments  The comments that will populate the Commercial Invoice (or Pro Forma).
     * @param  ?string  $purpose  This field is used for calculation of duties and taxes.
     * @param  ?FreightChargeMoney  $freightCharge  Any freight charges that are associated with this shipment.
     * @param  ?TaxesOrMiscellaneousCharges  $taxesOrMiscellaneousCharge  Any taxes or miscellaneous charges other than Freight charges or Insurance charges, that are associated with this shipment.
     * @param  ?string  $taxesOrMiscellaneousChargeType  Specifice the kind of tax or miscellaneous charge being reported on a Commercial Invoice.
     * @param  ?PackingCostCharges  $packingCosts  Any packing costs that are associated with this shipment.
     * @param  ?HandlingCostCharges  $handlingCosts  Any handling costs that are associated with this shipment.
     * @param  ?string  $specialInstructions  The special instructions that will populate the Commercial Invoice (or Pro Forma).<br>Example: specialInstructions
     * @param  ?string  $declarationStatement  The declaration statement that will populate the Commercial Invoice (or Pro Forma).<br> Max length is 554<br>Example: declarationStatement
     * @param  ?string  $paymentTerms  The payment terms that will populate the Commercial Invoice (or Pro Forma).  This field is being supported for completeness only.<br>Example: payment terms
     * @param  ?string  $purposeOfShipmentDescription  This is the reason for the shipment.<br>Note: SOLD is not a valid purpose for a Proforma Invoice.
     * @param  ?CustomerReferences  $customerReferences  These are additional customer reference data for commercial invoice.
     * @param  ?string  $originatorName  The originatorName that will populate the Commercial Invoice (or Pro Forma).
     */
    public function __construct(
        public ?string $termsOfSale = null,
        public ?array $comments = null,
        public ?string $purpose = null,
        public ?FreightChargeMoney $freightCharge = null,
        public ?TaxesOrMiscellaneousCharges $taxesOrMiscellaneousCharge = null,
        public ?string $taxesOrMiscellaneousChargeType = null,
        public ?PackingCostCharges $packingCosts = null,
        public ?HandlingCostCharges $handlingCosts = null,
        public ?string $specialInstructions = null,
        public ?string $declarationStatement = null,
        public ?string $paymentTerms = null,
        public ?string $purposeOfShipmentDescription = null,
        public ?CustomerReferences $customerReferences = null,
        public ?string $originatorName = null,
    ) {}
}
