<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ConsolidationV1\Dto;

use ShipStream\FedEx\Dto;

final class DistributionLocations extends Dto
{
    /**
     * @param  ?string  $type  Specifies the type of distribution locations.
     * @param  ?int  $locationNumber  Specifies the location number.
     * @param  ?string  $id  This is a customer-specified or system-assigned identifier that uniquely identifies the specific distibution location within a collection of distribution locations. This is not the same as the FedEx locationId or locationNumber..<br> Example: 123
     * @param  ?string  $locationId  The unique location identifier <br> Example: YBZA
     * @param  ?ContactAndAddress  $locationContactAndAddress  Idicates the contact and address details of a location.
     * @param  ?string  $clearanceNumber  This specifies the clearance number associated with the distribution location.<br> Example: 123
     * @param  ?string[]  $inclusionSpecifications  Specifies which kinds of shipments will be processed by this distribution location.
     */
    public function __construct(
        public ?string $type = null,
        public ?int $locationNumber = null,
        public ?string $id = null,
        public ?string $locationId = null,
        public ?ContactAndAddress $locationContactAndAddress = null,
        public ?string $clearanceNumber = null,
        public ?array $inclusionSpecifications = null,
    ) {}
}
