<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ConsolidationV1\Dto;

use ShipStream\FedEx\Dto;

final class DocTabZoneSpecification extends Dto
{
    /**
     * @param  ?int  $zoneNumber  is a nonNegativeInteger<br>Example:  1
     * @param  ?string  $header  header of DocTabZoneSpecification<br>Example:  WHT
     * @param  ?string  $dataField  dataField of DocTabZoneSpecification<br>Example:  REQUEST/PACKAGE/weight/Value
     * @param  ?string  $literalValue  literalValue of DocTabZoneSpecification<br>
     * @param  ?string  $justification  Doc Tab Zone Justification Type
     */
    public function __construct(
        public readonly ?int $zoneNumber = null,
        public readonly ?string $header = null,
        public readonly ?string $dataField = null,
        public readonly ?string $literalValue = null,
        public readonly ?string $justification = null,
    ) {
    }
}
