<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ConsolidationV1\Dto;

use ShipStream\FedEx\Dto;

final class DocumentGenerationDetail extends Dto
{
    /**
     * @param  ?string  $letterhead  Indicates the letterhead requirement type.
     * @param  ?string  $electronicSignature  Indicates electronic signature requirement type.
     * @param  ?int  $minimumCopiesRequired  Is a non negative integer.
     * @param  ?string  $type  Is an Enterprise Document Type.
     */
    public function __construct(
        public readonly ?string $letterhead = null,
        public readonly ?string $electronicSignature = null,
        public readonly ?int $minimumCopiesRequired = null,
        public readonly ?string $type = null,
    ) {
    }
}
