<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ConsolidationV1\Dto;

use ShipStream\FedEx\Dto;

final class FullSchemaConfirmConsolidation extends Dto
{
    /**
     * @param  LabelSpecification  $labelSpecification  These are label specification details includes the image type, printer format, and label stock for label. Can also specify specific details such as doc-tab content, regulatory labels, and masking data on the label.<br> Mandatory as it is needed during confirming consolidation. If it is not passed while creating consolidation it will fail during confirming consolidation.
     * @param  ConsolidationKey  $consolidationKey  Identifies the consolidation to which this open shipment should be added after successful creation.
     * @param  string  $processingOptionType  Specifying the processing option.
     * @param  PartyAccountNumber  $accountNumber  Specify the assigned FedEx Account Number. If the transportation charges to be billed to a payor other than the sender or recipient, provide the FedEx account number.
     * @param  ?string  $edtRequestType  Specifies whether the customer wishes to have Estimated Duties and Taxes provided with the rate quotation on this shipment.Only applies with shipments movinf under International Shipment
     * @param  ?string  $rateRequestType  Specifies the rate request type for the consolidation
     * @param  ?ConsolidationDocumentSpec  $consolidationDocumentSpecification  Details of consolidation document specification
     */
    public function __construct(
        public readonly LabelSpecification $labelSpecification,
        public readonly ConsolidationKey $consolidationKey,
        public readonly string $processingOptionType,
        public readonly PartyAccountNumber $accountNumber,
        public readonly ?string $edtRequestType = null,
        public readonly ?string $rateRequestType = null,
        public readonly ?ConsolidationDocumentSpec $consolidationDocumentSpecification = null,
    ) {
    }
}
