<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ConsolidationV1\Dto;

use ShipStream\FedEx\Dto;

final class FullSchemaConfirmConsolidationResults extends Dto
{
    /**
     * @param  PartyAccountNumber  $accountNumber  Specify the assigned FedEx Account Number. If the transportation charges to be billed to a payor other than the sender or recipient, provide the FedEx account number.
     * @param  string  $jobId  When the confirm consolidation is processed asynchronously, job Id is generated which is passed in confirm consolidation results to get complete consolidation results
     */
    public function __construct(
        public PartyAccountNumber $accountNumber,
        public string $jobId,
    ) {}
}
