<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ConsolidationV1\Dto;

use ShipStream\FedEx\Dto;

final class HazardousCommodityDescription extends Dto
{
    /**
     * @param  bool  $reportableQuantity  Reportable Quantity
     * @param  string  $packingGroup  Identifies DOT packing group for a hazardous commodity
     * @param  ?int  $sequenceNumber  RequiredSpecify the sequence number.
     * @param  ?string[]  $processingOptions  Indicates any special processing options to be applied to the description of the dangerous goods commodity
     * @param  ?string[]  $subsidiaryClasses  Required. Provides list of subsidiary classes
     * @param  ?string  $labelText  Specifies the text for the label.
     * @param  ?string  $technicalName  'The element specifies the technical name for the hazardous material.'
     * @param  ?HazardousCommodityPackingDetail  $packingDetails  Specifies documentation and limits for validation of an individual packing group/category. DG Data Upload Mode: Required (IATA), Optional (Other), DG Full Validation Mode: Required (IATA), Optional (Other),
     * @param  ?string  $authorization  Authorization
     * @param  ?float  $percentage  Percentage
     * @param  ?string  $id  ID
     * @param  ?string  $properShippingName  The proper shipping name as defined by the regulation. The name can also include qualifying words
     * @param  ?string  $hazardClass  'Specifies the hazard class for the commodity.'
     */
    public function __construct(
        public bool $reportableQuantity,
        public string $packingGroup,
        public ?int $sequenceNumber = null,
        public ?array $processingOptions = null,
        public ?array $subsidiaryClasses = null,
        public ?string $labelText = null,
        public ?string $technicalName = null,
        public ?HazardousCommodityPackingDetail $packingDetails = null,
        public ?string $authorization = null,
        public ?float $percentage = null,
        public ?string $id = null,
        public ?string $properShippingName = null,
        public ?string $hazardClass = null,
    ) {}
}
