<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ConsolidationV1\Dto;

use ShipStream\FedEx\Dto;

final class InternationalControlledExportDetail extends Dto
{
    /**
     * @param  ?string  $type  Indicates if consolidation is goods moving under a US Department of State(DOS) license, US Drug Enforcement Administration(DEA) export permit, bonded shipments moving under a CBP-7512 from a FTZ and/or bonded warehouse.
     * @param  ?string  $foreignTradeZoneCode  Foreign Trade Zone(FTZ) code which is a designated geographical commercial area where foreign merchandise is imported and stored without immediate requirement for duty payments.
     * @param  ?string  $entryNumber  The entry number is 11 digits and is comprised of the 3-character filer code, followed by the 7-digit entry number, and completed with the one digit check digit.
     * @param  ?string  $licenseOrPermitNumber  State Department License Number or DEA Permit Number
     * @param  ?string  $licenseOrPermitExpirationDate  Indicates the State Department License or DEA Permit expiration date. Format: YYYY-MM-DD
     */
    public function __construct(
        public ?string $type = null,
        public ?string $foreignTradeZoneCode = null,
        public ?string $entryNumber = null,
        public ?string $licenseOrPermitNumber = null,
        public ?string $licenseOrPermitExpirationDate = null,
    ) {}
}
