<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ConsolidationV1\Dto;

use ShipStream\FedEx\Dto;

final class LicenseOrPermitDetail extends Dto
{
    /**
     * @param  ?string  $number  Specifies License Or PermitDetail number.
     * @param  ?string  $effectiveDate  Specifies Effective Date.<br>Format [YYYY-MM-DD]
     * @param  ?string  $expirationDate  Specifies Expiration Date.<br>Format [YYYY-MM-DD]<br>Example: 2019-04-09
     */
    public function __construct(
        public ?string $number = null,
        public ?string $effectiveDate = null,
        public ?string $expirationDate = null,
    ) {}
}
