<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ConsolidationV1\Dto;

use ShipStream\FedEx\Dto;

final class Locale extends Dto
{
    /**
     * @param  ?string  $country  Country<br>Example: US
     * @param  ?string  $language  Language<br>Example: en
     */
    public function __construct(
        public ?string $country = null,
        public ?string $language = null,
    ) {}
}
