<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ConsolidationV1\Dto;

use ShipStream\FedEx\Dto;

final class PackageRateDetail extends Dto
{
    protected static array $complexArrayTypes = ['surcharges' => Surcharge::class];

    /**
     * @param  ?string  $ratedWeightMethod  Indicates which weight was used in calculating this rate, such as actual weight or dimensional weight.
     * @param  ?float  $totalFreightDiscounts  The sum of all discounts on this package.
     * @param  ?float  $totalTaxes  The sum of all taxes on this package.
     * @param  ?string  $minimumChargeType  Indicates the type for minumum charges. INTERNAL FEDEX USE ONLY.
     * @param  ?float  $baseCharge  The transportation charge only (prior to any discounts applied) for this package.
     * @param  ?float  $totalRebates  Specifies Total Rebates on this package.
     * @param  ?string  $rateType  Type used for this specific set of rate data.
     * @param  ?Weight  $billingWeight  Indicate the shipment total weight in pounds.<br>Example: 10.6<br>Note: <ul><li>This only applies to International shipments and should be used on the first package of a multiple piece shipment.</li><li>This value contains 1 explicit decimal position.</li><li>For one Label at a time shipments, the unit of totalWeight is considered same as the unit of weight provided in requestedPackageLineItem field.</li></ul>
     * @param  ?float  $netFreight  This is base charge minus total freight discounts for a package.
     * @param  Surcharge[]|null  $surcharges  All surcharges that apply to this shipment.<br><a onclick='loadDocReference("surcharges")'>click here to see Surcharges</a>
     * @param  ?float  $totalSurcharges  The total amount of all surcharges applied to this shipment.<br>Example: 9.88
     * @param  ?float  $netFedExCharge  This is sum of net freight and total surcharges (not including totalTaxes) for this package.
     * @param  ?float  $netCharge  This is the sum of net freight, total surcharges and total taxes for a package.
     * @param  ?string  $currency  The currency code. <a href="/developer-portal/en-us/reference-guide.html#currencycodes" target="_blank">Click here to see Currency Codes</a>
     */
    public function __construct(
        public readonly ?string $ratedWeightMethod = null,
        public readonly ?float $totalFreightDiscounts = null,
        public readonly ?float $totalTaxes = null,
        public readonly ?string $minimumChargeType = null,
        public readonly ?float $baseCharge = null,
        public readonly ?float $totalRebates = null,
        public readonly ?string $rateType = null,
        public readonly ?Weight $billingWeight = null,
        public readonly ?float $netFreight = null,
        public readonly ?array $surcharges = null,
        public readonly ?float $totalSurcharges = null,
        public readonly ?float $netFedExCharge = null,
        public readonly ?float $netCharge = null,
        public readonly ?string $currency = null,
    ) {
    }
}
