<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ConsolidationV1\Dto;

use ShipStream\FedEx\Dto;

final class RateDiscount extends Dto
{
    /**
     * @param  ?string  $rateDiscountType  Indicates the type.
     * @param  ?string  $description  Indicates the description for the rate discount.
     * @param  ?Money  $amount  This is commodity value used for Customs declaration.
     */
    public function __construct(
        public ?string $rateDiscountType = null,
        public ?string $description = null,
        public ?Money $amount = null,
        public ?float $percent = null,
    ) {}
}
