<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ConsolidationV1\Dto;

use ShipStream\FedEx\Dto;

final class RateDiscount extends Dto
{
    /**
     * @param  ?float  $amount  Specifies the amount.
     * @param  ?string  $rateDiscountType  The type of rate discount. <br/> Valid Values are BONUS, COUPON,EARNED,OTHER,VOLUME.
     * @param  ?float  $percent  Specifies the percentage of Rate discount.
     * @param  ?string  $description  Specifies the description of the discounted rate.
     */
    public function __construct(
        public ?float $amount = null,
        public ?string $rateDiscountType = null,
        public ?float $percent = null,
        public ?string $description = null,
    ) {}
}
