<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ConsolidationV1\Dto;

use ShipStream\FedEx\Dto;

final class RequestedConsolidationSpecialServicesRequested extends Dto
{
    /**
     * @param  ?string  $specialServiceTypes  Provides all the special service types.<br> Example: PRIORITY_ALERT
     * @param  ?PriorityAlertDetail  $priorityAlertDetail  specifies the Priority Alert Detail.
     */
    public function __construct(
        public readonly ?string $specialServiceTypes = null,
        public readonly ?PriorityAlertDetail $priorityAlertDetail = null,
    ) {
    }
}
