<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ConsolidationV1\Dto;

use ShipStream\FedEx\Dto;

final class RetrievedConsolidation extends Dto
{
    protected static array $complexArrayTypes = [
        'trackingIds' => TrackingIds::class,
        'customerReferences' => CustomerReferences::class,
    ];

    /**
     * @param  ?string  $consolidationType  Specifies the consolidation type.
     * @param  ?string  $shipDate  This field indicates the shipping date of the LTL Shipment
     * @param  TrackingIds[]|null  $trackingIds  The field is present to allow use of preassigned Master Airway Bill tracking number.
     * @param  ?ShipperParty  $shipper  The descriptive information for the customer shipping the package along with the physical location from where the shipment originates.
     * @param  ?Origin  $origin  The descriptive information for the customer origin.
     * @param  ?SoldToParty  $soldTo  Will indicate the party responsible for purchasing the goods shipped from the shipper to the recipient. The sold to party is not necessarily the recipient or the importer of record. The sold to party is relevant when the purchaser, rather than the recipient determines when certain customs regulations apply.
     * @param  ?string  $bookingNumber  Specifies the booking number needed to reserve package placement on a FedEx plane. Is a 12 digit number.
     * @param  ?ConsolidationDataSources  $consolidationDataSources  Specifies how selected values in the consolidation are to be determined.
     * @param  CustomerReferences[]|null  $customerReferences
     * @param  ?LabelSpecification  $labelSpecification  These are label specification details includes the image type, printer format, and label stock for label. Can also specify specific details such as doc-tab content, regulatory labels, and masking data on the label.<br> Mandatory as it is needed during confirming consolidation. If it is not passed while creating consolidation it will fail during confirming consolidation.
     * @param  ?InternationalDistributionDetail  $internationalDistributionDetail  Specifies the international distribution detail.
     * @param  ?TransborderDistributionDetail  $transborderDistributionDetail  Specifies attributes of a shipment whithin a transborder distribution.
     * @param  ?CustomsClearanceDetail  $customsClearanceDetail  Required for International and intra-country Shipments. Information about this package that only applies to an international (export) shipment or return.
     * @param  ?ConsolidationDocumentSpec  $consolidationDocumentSpecification  Details of consolidation document specification
     * @param  ?DistributionLocations  $distributionLocations  Specifies the distribution locations for consolidation.<br> Mandatory for International Ground Distribution.
     * @param  ?Payment  $shippingChargesPayment  Details about who and how the shipment will be paid for. 'payor' is optional when 'paymentType' provided is SENDER.
     * @param  ?SpecialServicesRequested  $specialServicesRequested  These special services are available at the shipment level for some or all service types.
     */
    public function __construct(
        public readonly ?string $consolidationType = null,
        public readonly ?string $shipDate = null,
        public readonly ?array $trackingIds = null,
        public readonly ?ShipperParty $shipper = null,
        public readonly ?Origin $origin = null,
        public readonly ?SoldToParty $soldTo = null,
        public readonly ?string $bookingNumber = null,
        public readonly ?ConsolidationDataSources $consolidationDataSources = null,
        public readonly ?array $customerReferences = null,
        public readonly ?LabelSpecification $labelSpecification = null,
        public readonly ?InternationalDistributionDetail $internationalDistributionDetail = null,
        public readonly ?TransborderDistributionDetail $transborderDistributionDetail = null,
        public readonly ?CustomsClearanceDetail $customsClearanceDetail = null,
        public readonly ?ConsolidationDocumentSpec $consolidationDocumentSpecification = null,
        public readonly ?DistributionLocations $distributionLocations = null,
        public readonly ?Payment $shippingChargesPayment = null,
        public readonly ?SpecialServicesRequested $specialServicesRequested = null,
    ) {
    }
}
