<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ConsolidationV1\Dto;

use ShipStream\FedEx\Dto;

final class ShippingDocument extends Dto
{
    protected static array $complexArrayTypes = ['parts' => ShippingDocumentParts::class];

    /**
     * @param  ?string  $type  The type of label being used for the package
     * @param  ?string  $shippingDocumentDisposition  Use this object to provide all data required for additional (non-label) shipping documents to be produced.
     * @param  ?string  $imageType  Specify the image format used for a shipping document.<br><a onclick='loadDocReference("labelstocktypes")'>click here to see label format types</a>
     * @param  ?int  $resolution  Specifies the image resolution in DPI (Dots per inch).
     * @param  ?int  $copiesToPrint  Indicates the number of copies to print. It can be zero for document with disposition as <i>no content</i> is included.
     * @param  ShippingDocumentParts[]|null  $parts  Indicates documentation part details.
     */
    public function __construct(
        public ?string $type = null,
        public ?string $shippingDocumentDisposition = null,
        public ?string $imageType = null,
        public ?int $resolution = null,
        public ?int $copiesToPrint = null,
        public ?array $parts = null,
    ) {}
}
