<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ConsolidationV1\Dto;

use ShipStream\FedEx\Dto;

final class TrackingIds extends Dto
{
    /**
     * @param  string  $trackingIdType  Specify the FedEx transportation type (EXPRESS, GROUND, FREIGHT).
     * @param  string  $formId  This is FedEx tracking Identifier associated with the package.
     * @param  string  $trackingNumber  This is a number associated with a package that is used to track it.
     */
    public function __construct(
        public readonly string $trackingIdType,
        public readonly string $formId,
        public readonly string $trackingNumber,
    ) {
    }
}
