<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ConsolidationV1\Dto;

use ShipStream\FedEx\Dto;

final class TransborderDistributionDetailSpecialServicesRequestedTransborderDistributionLtlDetailPaymentCreditCardTransactionDetailFraudDetectionDetail extends Dto
{
    /**
     * @param  ?string  $ipAddress  IP address
     * @param  ?bool  $clientCookiesEnabled  Client cookies enabled or not
     * @param  ?string  $devicePrint  The html that a client needs to embed for triggering a call to cyber source for needed information on device identification
     */
    public function __construct(
        public readonly ?string $ipAddress = null,
        public readonly ?bool $clientCookiesEnabled = null,
        public readonly ?string $devicePrint = null,
    ) {
    }
}
