<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ConsolidationV1\Dto;

use ShipStream\FedEx\Dto;

final class TransborderDistributionDetailSpecialServicesRequestedTransborderDistributionLtlDetailPaymentCreditCardCreditCardHolderContact extends Dto
{
    /**
     * @param  ?TransborderDistributionDetailSpecialServicesRequestedTransborderDistributionLtlDetailPaymentCreditCardCreditCardHolderContactPersonName  $personName  Credit card holder's name
     * @param  ?string  $phoneNumberCountryCode  Country code for credit card holder's phone number
     * @param  ?string  $phoneNumberAreaCode  Area code for credit card holder's phone number
     * @param  ?string  $emailAddress  Specify EmailAddress.
     * @param  ?string  $phoneNumber  Specify Phone Number.
     * @param  ?string  $phoneExtension  Specify Phone Extension.
     * @param  ?string  $companyName  Specify Company Name.
     * @param  ?string  $pagerNumber  Specify Pager Number.
     * @param  ?string  $faxNumber  Specify Fax Number.
     * @param  ?string  $title  Specify the Title of the Contact.
     */
    public function __construct(
        public ?TransborderDistributionDetailSpecialServicesRequestedTransborderDistributionLtlDetailPaymentCreditCardCreditCardHolderContactPersonName $personName = null,
        public ?string $phoneNumberCountryCode = null,
        public ?string $phoneNumberAreaCode = null,
        public ?string $emailAddress = null,
        public ?string $phoneNumber = null,
        public ?string $phoneExtension = null,
        public ?string $companyName = null,
        public ?string $pagerNumber = null,
        public ?string $faxNumber = null,
        public ?string $title = null,
    ) {}
}
