<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ConsolidationV1\Dto;

use ShipStream\FedEx\Dto;

final class TransactionConsolidationShipmentResultsOutputVo extends Dto
{
    protected static array $complexArrayTypes = [
        'shipmentDocuments' => LabelResponseVo::class,
        'pieceResponses' => PieceResponse::class,
    ];

    /**
     * @param  ?string  $serviceType  Identifies the service for this shipment<br>Example: FEDEX_2_DAY_FREIGHT<br><a href="/developer-portal/en-us/reference-guide.html#servicetypes" target="_blank">Click here to see Service Types</a>
     * @param  ?string  $shipDateStamp  Specifies shipment date. Format [YYYY-MM-DD]<br>Example: 2010-03-04
     * @param  ?string  $serviceCategory  Specifies Service Category.<br>Example: EXPRESS
     * @param  LabelResponseVo[]|null  $shipmentDocuments
     * @param  PieceResponse[]|null  $pieceResponses
     * @param  ?string  $serviceName  Describes the service name for the shipment<br>Example: FedEx 2 Day Freight
     * @param  ?ConsolidationCompletedShipmentDetail  $completedShipmentDetail  Returns the result of processing the desired package as a single-package shipment.
     * @param  ?ShipmentAdvisoryDetails  $shipmentAdvisoryDetails  These are shipment advisory details.
     * @param  ?string  $masterTrackingNumber  Indicates the TrackingNumber for the single or multiple-package shipment<br>Example: 794953535000
     */
    public function __construct(
        public ?string $serviceType = null,
        public ?string $shipDateStamp = null,
        public ?string $serviceCategory = null,
        public ?array $shipmentDocuments = null,
        public ?array $pieceResponses = null,
        public ?string $serviceName = null,
        public ?ConsolidationCompletedShipmentDetail $completedShipmentDetail = null,
        public ?ShipmentAdvisoryDetails $shipmentAdvisoryDetails = null,
        public ?string $masterTrackingNumber = null,
    ) {}
}
