<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ConsolidationV1\Dto;

use ShipStream\FedEx\Dto;

final class TransborderDistributionDetailSpecialServicesRequestedTransborderDistributionLtlDetailPaymentPayor extends Dto
{
    protected static array $complexArrayTypes = [
        'associatedAccounts' => TransborderDistributionDetailSpecialServicesRequestedTransborderDistributionLtlDetailPaymentPayorAssociatedAccounts::class,
    ];

    /**
     * @param  ?TransborderDistributionDetailSpecialServicesRequestedTransborderDistributionLtlDetailPaymentPayorResponsibleParty  $responsibleParty  The descriptive information for the person who is responsible for the shipment.
     * @param  TransborderDistributionDetailSpecialServicesRequestedTransborderDistributionLtlDetailPaymentPayorAssociatedAccounts[]|null  $associatedAccounts  Other associated accounts
     */
    public function __construct(
        public ?TransborderDistributionDetailSpecialServicesRequestedTransborderDistributionLtlDetailPaymentPayorResponsibleParty $responsibleParty = null,
        public ?array $associatedAccounts = null,
    ) {}
}
