<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ConsolidationV1\Dto;

use ShipStream\FedEx\Dto;

final class TransborderDistributionDetailSpecialServicesRequestedTransborderDistributionLtlDetailPaymentCreditCardCreditCardHolderContactPersonName extends Dto
{
    /**
     * @param  ?string  $prefix  Prefix for the credit card holder
     * @param  ?string  $title  Title for the credit card holder
     * @param  ?string  $firstName  First name of the credit card holder
     * @param  ?string  $middleName  Middle name of the credit card holder
     * @param  ?string  $lastName  Last name of the credit card holder
     * @param  ?string  $suffix  Suffix for the credit card holder
     */
    public function __construct(
        public ?string $prefix = null,
        public ?string $title = null,
        public ?string $firstName = null,
        public ?string $middleName = null,
        public ?string $lastName = null,
        public ?string $suffix = null,
    ) {}
}
