<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ConsolidationV1\Dto;

use ShipStream\FedEx\Dto;

final class TransborderDistributionDetail2 extends Dto
{
    /**
     * @param  ?TransborderDistributionDetail1SpecialServicesRequested  $specialServicesRequested  Specifies special services to be performed on this shipment as part of a transborder distribution.
     * @param  ?string  $routing  Specifies the transborder distribution routing.
     * @param  ?SummaryDetail  $summaryDetail  Package type, number, and weight details
     */
    public function __construct(
        public ?TransborderDistributionDetail1SpecialServicesRequested $specialServicesRequested = null,
        public ?string $routing = null,
        public ?SummaryDetail $summaryDetail = null,
    ) {}
}
