<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ConsolidationV1\Dto;

use ShipStream\FedEx\Dto;

final class TransborderDistributionDetailSpecialServicesRequestedTransborderDistributionLtlDetailPaymentPayorResponsiblePartyContact extends Dto
{
    /**
     * @param  ?string  $contactId  Client provided identifier corresponding to this contact information.
     * @param  ?string  $personName  Specify Person Name.
     * @param  ?string  $tollFreePhoneNumber  Specify Toll Free PhoneNumber.
     * @param  ?string  $emailAddress  Specify Email Address.
     * @param  ?string  $phoneNumber  Specify Phone Number.
     * @param  ?string  $phoneExtension  Specify Phone Extension.
     * @param  ?string  $companyName  Specify Company Name.
     * @param  ?string  $faxNumber  Specify Fax Number.
     * @param  ?string  $pagerNumber  Specify Pager Number.
     * @param  ?string  $title  Specify the Title of the Contact.
     */
    public function __construct(
        public readonly ?string $contactId = null,
        public readonly ?string $personName = null,
        public readonly ?string $tollFreePhoneNumber = null,
        public readonly ?string $emailAddress = null,
        public readonly ?string $phoneNumber = null,
        public readonly ?string $phoneExtension = null,
        public readonly ?string $companyName = null,
        public readonly ?string $faxNumber = null,
        public readonly ?string $pagerNumber = null,
        public readonly ?string $title = null,
    ) {
    }
}
