<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ConsolidationV1\Dto;

use ShipStream\FedEx\Dto;

final class VariableHandlingCharges extends Dto
{
    /**
     * @param  ?Money  $variableHandlingCharge  This is commodity value used for Customs declaration.
     * @param  ?Money  $fixedVariableHandlingCharge  This is commodity value used for Customs declaration.
     * @param  ?Money  $percentVariableHandlingCharge  This is commodity value used for Customs declaration.
     * @param  ?Money  $totalCustomerCharge  This is commodity value used for Customs declaration.
     */
    public function __construct(
        public ?Money $variableHandlingCharge = null,
        public ?Money $fixedVariableHandlingCharge = null,
        public ?Money $percentVariableHandlingCharge = null,
        public ?Money $totalCustomerCharge = null,
    ) {}
}
