<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ShipDGHazmatV1\Dto;

use ShipStream\FedEx\Dto;

final class BaseProcessOutputVo extends Dto
{
    protected static array $complexArrayTypes = [
        'transactionShipments' => TransactionShipmentOutputVo::class,
        'alerts' => Alert::class,
    ];

    /**
     * @param  ?string  $customerTransactionId  This element allows you to assign a unique identifier to your transaction.  This element is also returned in the reply and helps you match the request to the reply.<br>Example:AnyCo_order123456789
     * @param  TransactionShipmentOutputVo[]|null  $transactionShipments  The shipping transaction details, such as master tracking number, service type, and ship timestamp.
     * @param  ?MasterLabelResponse  $masterMergeLabelandDocuments  If Ship request has both an outbound shipment and "returnRequestedShipment" included, this indicates the combined outbound and return labels and documents and provided in a single PDF, So customer can print it in one shot.
     * @param  ?mixed[]  $transactionDetail  Transaction Detail
     * @param  Alert[]|null  $alerts  The alerts received when a shipShipment is processed. This includes the alert code, alert type, and alert message.
     */
    public function __construct(
        public ?string $customerTransactionId = null,
        public ?array $transactionShipments = null,
        public ?string $jobId = null,
        public ?MasterLabelResponse $masterMergeLabelandDocuments = null,
        public ?array $transactionDetail = null,
        public ?array $alerts = null,
    ) {}
}
