<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ShipDGHazmatV1\Dto;

use ShipStream\FedEx\Dto;

final class Contact2 extends Dto
{
    /**
     * @param  ?string  $personName  Specify Person Name.<br>Example: John Taylor
     * @param  ?string  $tollFreePhoneNumber  Specify Toll Free PhoneNumber.<br>Example: 6127812
     * @param  ?string  $emailAddress  Specify EmailAddress.<br>Example: sample@company.com
     * @param  ?string  $phoneNumber  The shippers phone number. <br>Minimum length is 10 and supports maximum of 15 for certain countries using longer phone numbers.<br>Note: For US and CA, a phone number must have exactly 10 digits, plus an optional leading country code of "1" or "+1".<br>Example: 918xxxxx890
     * @param  ?string  $phoneExtension  Specify Phone Extension.<br>Example: 91
     * @param  ?string  $companyName  Specify Company Name.<br>Example: Fedex
     * @param  ?string  $pagerNumber  Specify Pager Number.<br>Example: 6127812
     * @param  ?string  $faxNumber  Specify Fax Number.<br>Example: 1234567890
     * @param  ?string  $title  Specify the Title of the Contact.<br>Example: title
     */
    public function __construct(
        public ?string $personName = null,
        public ?string $tollFreePhoneNumber = null,
        public ?string $emailAddress = null,
        public ?string $phoneNumber = null,
        public ?string $phoneExtension = null,
        public ?string $companyName = null,
        public ?string $pagerNumber = null,
        public ?string $faxNumber = null,
        public ?string $title = null,
    ) {}
}
