<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ShipDGHazmatV1\Dto;

use ShipStream\FedEx\Dto;

final class DangerousGoodsDetailInfectiousSubstanceResponsibleContact extends Dto
{
    /**
     * @param  ?string  $contactId  Indicates the contact id.
     * @param  ?string  $personName  Name of the contact person
     * @param  ?string  $title  Title of the contact person
     * @param  ?string  $companyName  Company name of the contact person
     * @param  ?string  $phoneNumber  The phone number of the contact person
     * @param  ?string  $phoneExtension  The phone number extension
     * @param  ?string  $tollFreePhoneNumber  A toll free number that can be used to reach the responsible party
     * @param  ?string  $pagerNumber  The pager number of the contact person
     * @param  ?string  $faxNumber  The fax number of the contact person
     * @param  ?string  $eMailAddress  The email address of the contact person
     */
    public function __construct(
        public ?string $contactId = null,
        public ?string $personName = null,
        public ?string $title = null,
        public ?string $companyName = null,
        public ?string $phoneNumber = null,
        public ?string $phoneExtension = null,
        public ?string $tollFreePhoneNumber = null,
        public ?string $pagerNumber = null,
        public ?string $faxNumber = null,
        public ?string $eMailAddress = null,
    ) {}
}
