<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ShipDGHazmatV1\Dto;

use ShipStream\FedEx\Dto;

final class DangerousGoodsDetailRadioactivityDetail extends Dto
{
    /**
     * @param  ?float  $transportIndex  Specifies the maximum radiation level from the dangerous goods.
     * @param  ?float  $surfaceReading  The radiation of the pacakage at the package surface.
     * @param  ?float  $criticalitySafetyIndex  The criticality safety index(CSI) is a number assigned to a package containing fissile material and is used to provide control over the accumulation of packages.
     */
    public function __construct(
        public ?float $transportIndex = null,
        public ?float $surfaceReading = null,
        public ?float $criticalitySafetyIndex = null,
        public ?DangerousGoodsDetailRadioactivityDetailDimensions $dimensions = null,
    ) {}
}
