<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ShipDGHazmatV1\Dto;

use ShipStream\FedEx\Dto;

final class DangerousGoodsDetailSignatory extends Dto
{
    /**
     * @param  ?string  $contactName  The name of the person signing for this shipment.
     * @param  ?string  $title  The title of the person signing for this shipment.
     * @param  ?string  $place  Place of the person signing for this shipment.
     */
    public function __construct(
        public ?string $contactName = null,
        public ?string $title = null,
        public ?string $place = null,
    ) {}
}
