<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ShipDGHazmatV1\Dto;

use ShipStream\FedEx\Dto;

final class DestinationControlDetail extends Dto
{
    /**
     * @param  string  $statementTypes  Destination Control Statement Type
     * @param  ?string  $endUser  End User
     * @param  ?string[]  $destinationCountries  Destination Countries<br>Example: [US, India]
     */
    public function __construct(
        public string $statementTypes,
        public ?string $endUser = null,
        public ?array $destinationCountries = null,
    ) {}
}
