<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ShipDGHazmatV1\Dto;

use ShipStream\FedEx\Dto;

final class DocTabContentZone extends Dto
{
    protected static array $complexArrayTypes = ['docTabZoneSpecifications' => DocTabZoneSpecification::class];

    /**
     * @param  DocTabZoneSpecification[]|null  $docTabZoneSpecifications
     */
    public function __construct(
        public ?array $docTabZoneSpecifications = null,
    ) {}
}
