<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ShipDGHazmatV1\Dto;

use ShipStream\FedEx\Dto;

final class DocumentRequirementsDetail extends Dto
{
    protected static array $complexArrayTypes = ['generationDetails' => DocumentGenerationDetail::class];

    /**
     * @param  ?string[]  $requiredDocuments  Provides the required documents info.<br>Example: [COMMERCIAL_OR_PRO_FORMA_INVOICE,AIR_WAYBILL]
     * @param  ?string[]  $prohibitedDocuments  Provides the prohibited Documents info.<br>Example: [ USMCA_CERTIFICATION_OF_ORIGIN]
     * @param  DocumentGenerationDetail[]|null  $generationDetails  Provides the generation details.
     */
    public function __construct(
        public ?array $requiredDocuments = null,
        public ?array $prohibitedDocuments = null,
        public ?array $generationDetails = null,
    ) {}
}
