<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ShipDGHazmatV1\Dto;

use ShipStream\FedEx\Dto;

final class GeneralAgencyAgreementDetail extends Dto
{
    /**
     * @param  ?ShippingDocumentFormat  $documentFormat  Shipping Document Format, allow ImageType of PDF and StockType of OP_900_LL or ImageType of Text and StockType of OP_900_LL_B.  Other elements are optional
     */
    public function __construct(
        public ?ShippingDocumentFormat $documentFormat = null,
    ) {}
}
