<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ShipDGHazmatV1\Dto;

use ShipStream\FedEx\Dto;

final class HazardousCommodityDescription extends Dto
{
    /**
     * @param  bool  $reportableQuantity  Reportable Quantity
     * @param  string  $packingGroup  Identifies DOT packing group for a hazardous commodity
     * @param  ?int  $sequenceNumber  RequiredSpecify the sequence number<br>Example: 9812
     * @param  ?string[]  $processingOptions  Indicates any special processing options to be applied to the description of the dangerous goods commodity
     * @param  ?string[]  $subsidiaryClasses  Required
     *
     * Provides list of subsidiary classes<br>Example: ["Subsidiary Classes"]
     * @param  ?string  $labelText  Specifies the text for the label<br>Example: labelText'
     * @param  ?string  $technicalName  'The element specifies the technical name for the hazardous material<br>Example: technicalName'
     * @param  ?HazardousCommodityPackingDetail  $packingDetails  Specifies documentation and limits for validation of an individual packing group/category. DG Data Upload Mode: Required (IATA), Optional (Other), DG Full Validation Mode: Required (IATA), Optional (Other),
     * @param  ?string  $authorization  Authorization<br>Example: authorization
     * @param  ?float  $percentage  Percentage<br>Example: 12.45
     * @param  ?string  $id  ID<br>Example: 123
     * @param  ?string  $properShippingName  The proper shipping name as defined by the regulation. The name can also include qualifying words<br>Example: properShippingName
     * @param  ?string  $hazardClass  'Specifies the hazard class for the commodity<br>Example: hazard Class'
     */
    public function __construct(
        public bool $reportableQuantity,
        public string $packingGroup,
        public ?int $sequenceNumber = null,
        public ?array $processingOptions = null,
        public ?array $subsidiaryClasses = null,
        public ?string $labelText = null,
        public ?string $technicalName = null,
        public ?HazardousCommodityPackingDetail $packingDetails = null,
        public ?string $authorization = null,
        public ?float $percentage = null,
        public ?string $id = null,
        public ?string $properShippingName = null,
        public ?string $hazardClass = null,
    ) {}
}
