<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ShipDGHazmatV1\Dto;

use ShipStream\FedEx\Dto;

final class InternationalControlledExportDetail extends Dto
{
    /**
     * @param  string  $type  Indicates the International Controlled Export Type
     * @param  ?string  $licenseOrPermitExpirationDate  Indicates the license Or Permit Expiration Date.<br>Format YYYY-MM-DD <br>Example: "2019-12-03"
     * @param  ?string  $licenseOrPermitNumber  Indicates the licenseOrPermitNumber.<br>Example: 11
     * @param  ?string  $entryNumber  Indicates the entry number.<br>Example: 125
     * @param  ?string  $foreignTradeZoneCode  Indicates the ForeignTradeZoneCode.<br>Example: US
     */
    public function __construct(
        public string $type,
        public ?string $licenseOrPermitExpirationDate = null,
        public ?string $licenseOrPermitNumber = null,
        public ?string $entryNumber = null,
        public ?string $foreignTradeZoneCode = null,
    ) {}
}
