<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ShipDGHazmatV1\Dto;

use ShipStream\FedEx\Dto;

final class LabelResponseVo extends Dto
{
    protected static array $complexArrayTypes = ['alerts' => Alert::class];

    /**
     * @param  ?string  $contentKey  The content key for the document/label.<br>Example: content key
     * @param  ?int  $copiesToPrint  The number of copies to print for the specific document type<br>Example: 10
     * @param  ?string  $contentType  Indicates the type of document/label.
     * @param  ?string  $trackingNumber  This is a tracking number associted with this package. <br>Example: 49XXX0000XXX20032835
     * @param  ?string  $docType  The description of the document type.<br>Example: PDF
     * @param  Alert[]|null  $alerts
     * @param  ?string  $encodedLabel  Indicates document is encoded. <br>Example: encoded label
     * @param  ?string  $url  The URL of the shipping document/label<br>Example: https://wwwdev.idev.fedex.com/document/v2/document/retrieve/SH,794816968200_Merge/isLabel=true&autoPrint=false
     * @param  ?string  $barcodeLabelData  This is a unique identifier for generating QR code.
     */
    public function __construct(
        public ?string $contentKey = null,
        public ?int $copiesToPrint = null,
        public ?string $contentType = null,
        public ?string $trackingNumber = null,
        public ?string $docType = null,
        public ?array $alerts = null,
        public ?string $encodedLabel = null,
        public ?string $url = null,
        public ?string $barcodeLabelData = null,
    ) {}
}
