<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ShipDGHazmatV1\Dto;

use ShipStream\FedEx\Dto;

final class LabelSpecificationReturnedDispositionDetail extends Dto
{
    /**
     * @param  ?string  $type  Specifies disposition type.
     */
    public function __construct(
        public ?string $type = null,
    ) {}
}
