<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ShipDGHazmatV1\Dto;

use ShipStream\FedEx\Dto;

final class PackageSpecialServicesRequested extends Dto
{
    protected static array $attributeMap = ['packageCodDetail' => 'packageCODDetail'];

    protected static array $complexArrayTypes = [
        'batteryDetails' => BatteryDetail::class,
        'standaloneBatteryDetails' => StandaloneBatteryDetails::class,
    ];

    /**
     * @param  ?string[]  $specialServiceTypes  The list of all special services requested for the package.<br><a onclick='loadDocReference("packagelevelspecialservicetypes")'>Click here to see Package level Special Service Types</a>
     * @param  ?PriorityAlertDetail  $priorityAlertDetail  specifies the Priority Alert Detail.
     * @param  ?string  $signatureOptionType  Signature Option Type<br/>ADULT - Adult signature required, at recipient's address.<br/>DIRECT - Signature required, at recipient's address.<br>INDIRECT - Signature required, alternate address is accepted.<br/>NO_SIGNATURE_REQUIRED - Signature is not required.<br/>SERVICE_DEFAULT - Signature handled as per current Service Guide.
     * @param  ?SignatureOptionDetail  $signatureOptionDetail  Required for SignatureOptions.  Specifies the SignatureOptionDetail
     * @param  ?AlcoholDetail  $alcoholDetail  Specifies details for a package containing alcohol. Required for alcohol special service. The alcoholRecipientType is required.
     * @param  ?DangerousGoodsDetail  $dangerousGoodsDetail  Provides the details on the dangerous goods
     * @param  ?PackageCodDetail  $packageCodDetail  Conditional
     *
     * COD main information is set in shipment level.
     * @param  ?int  $pieceCountVerificationBoxCount  Piece Count Verification Box Count
     * @param  BatteryDetail[]|null  $batteryDetails  Provides details about the batteries or cells that are contained within this specific package.
     * @param  ?Weight  $dryIceWeight  These are the package weight details.
     * @param  StandaloneBatteryDetails[]|null  $standaloneBatteryDetails  Provide details about the batteries or cells that are contained within this specific package.
     */
    public function __construct(
        public ?array $specialServiceTypes = null,
        public ?PriorityAlertDetail $priorityAlertDetail = null,
        public ?string $signatureOptionType = null,
        public ?SignatureOptionDetail $signatureOptionDetail = null,
        public ?AlcoholDetail $alcoholDetail = null,
        public ?DangerousGoodsDetail $dangerousGoodsDetail = null,
        public ?PackageCodDetail $packageCodDetail = null,
        public ?int $pieceCountVerificationBoxCount = null,
        public ?array $batteryDetails = null,
        public ?Weight $dryIceWeight = null,
        public ?array $standaloneBatteryDetails = null,
    ) {}
}
