<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ShipDGHazmatV1\Dto;

use ShipStream\FedEx\Dto;

final class PhoneNumber extends Dto
{
    /**
     * @param  ?string  $areaCode  Indicates the Area Code of a phone number.
     * @param  ?string  $localNumber  Indicates the Local Number
     * @param  ?string  $extension  Identifies the phone extension associated with this contact.
     * @param  ?string  $countryCode  The two-letter code used to identify a country. Max length is 2.<br>Example: US<br><a onclick='loadDocReference("countrycodes")'>Click here to see Country Codes</a>
     * @param  ?string  $personalIdentificationNumber  Identifies a Personal Identification Number
     */
    public function __construct(
        public ?string $areaCode = null,
        public ?string $localNumber = null,
        public ?string $extension = null,
        public ?string $countryCode = null,
        public ?string $personalIdentificationNumber = null,
    ) {}
}
