<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ShipDGHazmatV1\Dto;

use ShipStream\FedEx\Dto;

final class RateDiscount extends Dto
{
    /**
     * @param  ?float  $amount  <br>Example 8.9
     * @param  ?string  $rateDiscountType  The type of rate discount. <br/> Valid Values are BONUS, COUPON,EARNED,OTHER,VOLUME.<br>Example COUPON
     * @param  ?float  $percent  Specifies the percentage of Rate discount.<br>Example 28.9
     * @param  ?string  $description  Specifies the description of the discounted rate.<br>Example: description
     */
    public function __construct(
        public ?float $amount = null,
        public ?string $rateDiscountType = null,
        public ?float $percent = null,
        public ?string $description = null,
    ) {}
}
