<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ShipDGHazmatV1\Dto;

use ShipStream\FedEx\Dto;

final class RegulatoryAdvisoryDetail extends Dto
{
    protected static array $complexArrayTypes = [
        'commodityClarifications' => CommodityClarificationDetail::class,
        'prohibitions' => RegulatoryProhibition::class,
    ];

    /**
     * @param  CommodityClarificationDetail[]|null  $commodityClarifications  This specifies the Commodity clarifications.
     * @param  RegulatoryProhibition[]|null  $prohibitions  This indicates the Regulatory probitions.
     */
    public function __construct(
        public ?array $commodityClarifications = null,
        public ?array $prohibitions = null,
    ) {}
}
