<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ShipDGHazmatV1\Dto;

use ShipStream\FedEx\Dto;

final class RequestedShipmentVerifyShipmentSpecialServices extends Dto
{
    protected static array $attributeMap = ['shipmentCodDetail' => 'shipmentCODDetail'];

    /**
     * @param  ?string[]  $specialServiceTypes  Indicate the Special services requested for this shipment.<br>Example: <ul><li>HOLD_AT_LOCATION</li><li>RETURN_SHIPMENT</li><li>BROKER_SELECT_OPTION</li><li>CALL_BEFORE_DELIVERY</li><li>COD</li><li>CUSTOM_DELIVERY_WINDOW</li></ul><br><a onclick='loadDocReference("shipmentlevelspecialservicetypes")'>click here to see Shipment Special Service Types</a>
     * @param  ?EtdDetail  $etdDetail  Use this object to specify all information on how the electronic Trade document references used with the shipment.
     * @param  ?ReturnShipmentDetail  $returnShipmentDetail  Use this object for specifying return shipment details.
     * @param  ?DeliveryOnInvoiceAcceptanceDetail  $deliveryOnInvoiceAcceptanceDetail  Indicate the Delivery On Invoice Acceptance detail. Recipient is required for Delivery On Invoice Special service.
     * @param  ?InternationalTrafficInArmsRegulationsDetail  $internationalTrafficInArmsRegulationsDetail  These are International Traffic In Arms Regulations shipment service details.
     * @param  ?PendingShipmentDetail  $pendingShipmentDetail  Required for email label return shipments.<br>This field is not applicable for CreateTag.<br>This object is used to specify the Pending Shipment Type for Email label.
     * @param  ?HoldAtLocationDetail  $holdAtLocationDetail  Use this object to specify required information for a shipment to be held at destination FedEx location.<br><i>Note: This object HoldAtLocationDetail is Required, when HOLD_AT_LOCATION is chosen in the specialServiceTypes.</i>
     * @param  ?ShipmentCodDetail  $shipmentCodDetail  Conditional<br>This is the shipment level COD detail.
     * @param  ?ShipmentDryIceDetail  $shipmentDryIceDetail  This is the descriptive data required for a FedEx shipment containing dangerous materials. This element is required when SpecialServiceType DRY_ICE is selected.<p><i>Note:<ul><li>Dry Ice is a Package level Special Service for Domestic and International shipments.</li><li>Dry Ice must be declared at both Shipment and Package level for International MPS shipments to print the compliance statement on Airway Bill labels.</li></ul></i></p>
     * @param  ?InternationalControlledExportDetail  $internationalControlledExportDetail  Use this object to specify International Controlled Export shipment Details.<br>Note: licenseOrPermitExpirationDate and licenseOrPermitNumber are not required when type is WAREHOUSE_WITHDRAWAL.
     * @param  ?HomeDeliveryPremiumDetail  $homeDeliveryPremiumDetail  Special service elements for FedEx Ground Home Delivery shipments.  If selected, 'homedeliveryPremiumType' is required.
     */
    public function __construct(
        public ?array $specialServiceTypes = null,
        public ?EtdDetail $etdDetail = null,
        public ?ReturnShipmentDetail $returnShipmentDetail = null,
        public ?DeliveryOnInvoiceAcceptanceDetail $deliveryOnInvoiceAcceptanceDetail = null,
        public ?InternationalTrafficInArmsRegulationsDetail $internationalTrafficInArmsRegulationsDetail = null,
        public ?PendingShipmentDetail $pendingShipmentDetail = null,
        public ?HoldAtLocationDetail $holdAtLocationDetail = null,
        public ?ShipmentCodDetail $shipmentCodDetail = null,
        public ?ShipmentDryIceDetail $shipmentDryIceDetail = null,
        public ?InternationalControlledExportDetail $internationalControlledExportDetail = null,
        public ?HomeDeliveryPremiumDetail $homeDeliveryPremiumDetail = null,
    ) {}
}
