<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ShipDGHazmatV1\Dto;

use ShipStream\FedEx\Dto;

final class ReturnEmailDetail extends Dto
{
    /**
     * @param  string  $merchantPhoneNumber  Required for Email Return Labels.<br> This is the merchant phone number.<br>Example: 19012635656
     * @param  ?string[]  $allowedSpecialService  Identifies the allowed (merchant-authorized) special services which may be selected when the subsequent shipment is created.<br> Only services represented in EmailLabelAllowedSpecialServiceType will be controlled by this list.
     */
    public function __construct(
        public string $merchantPhoneNumber,
        public ?array $allowedSpecialService = null,
    ) {}
}
