<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ShipDGHazmatV1\Dto;

use ShipStream\FedEx\Dto;

final class ServiceDescription extends Dto
{
    protected static array $complexArrayTypes = ['names' => ProductName::class];

    /**
     * @param  ?string  $serviceType  Indicates the type of service that is used to ship the package.<br>Example: FEDEX_1_DAY_FREIGHT<br>a onclick='loadDocReference("servicetypes")'>Click here to see Service Types</a>
     * @param  ?string  $code  Specifies code of the Service.<br>example: 80
     * @param  ProductName[]|null  $names  Branded, translated, and/or localized names for this service.
     * @param  ?string[]  $operatingOrgCodes  FOR FEDEX INTERNAL USE ONLY. The operating org code in a service.<br>Example: [FXE, FXE]
     * @param  ?string  $astraDescription  Specifies astra Description<br>Example: 2 DAY FRT
     * @param  ?string  $serviceId  FOR FEDEX INTERNAL USE ONLY, Designates the service ID.<br>Example: EP1000000027
     * @param  ?string  $serviceCategory  FOR FEDEX INTERNAL USE ONLY. This is tied to the Product EFS interface definition which will currently contain the values of parcel or freight.<br>Example: freight
     */
    public function __construct(
        public ?string $serviceType = null,
        public ?string $code = null,
        public ?array $names = null,
        public ?array $operatingOrgCodes = null,
        public ?string $astraDescription = null,
        public ?string $description = null,
        public ?string $serviceId = null,
        public ?string $serviceCategory = null,
    ) {}
}
