<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ShipDGHazmatV1\Dto;

use ShipStream\FedEx\Dto;

final class ShipmentCodDetail extends Dto
{
    /**
     * @param  ?CodTransportationChargesDetail  $addTransportationChargesDetail  This element allows you to add transportation charges to the C.O.D. collection amount. <br> Valid values are: ADD_ACCOUNT_COD_SURCHARGE, ADD_ACCOUNT_NET_CHARGE, ADD_ACCOUNT_NET_FREIGHT, ADD_ACCOUNT_TOTAL_CUSTOMER_CHARGE, ADD_LIST_COD_SURCHARGE, ADD_LIST_NET_CHARGE, ADD_LIST_NET_FREIGHT, ADD_LIST_TOTAL_CUSTOMER_CHARGE
     * @param  ?string  $remitToName  Specify the name of the person or company receiving the secured/unsecured funds payment<br>Example: remitToName
     * @param  ?string  $codCollectionType  Identifies the type of funds FedEx should collect upon shipment delivery
     * @param  ?ContactAndAddress  $financialInstitutionContactAndAddress  Specifies the contact and address details of a location.
     * @param  ?Money  $codCollectionAmount  This is commodity value used for Customs declaration.
     * @param  ?string  $returnReferenceIndicatorType  Indicates which type of reference information to include on the COD return shipping label.
     * @param  ?Money  $shipmentCodAmount  This is commodity value used for Customs declaration.
     */
    public function __construct(
        public ?CodTransportationChargesDetail $addTransportationChargesDetail = null,
        public ?Party $codRecipient = null,
        public ?string $remitToName = null,
        public ?string $codCollectionType = null,
        public ?ContactAndAddress $financialInstitutionContactAndAddress = null,
        public ?Money $codCollectionAmount = null,
        public ?string $returnReferenceIndicatorType = null,
        public ?Money $shipmentCodAmount = null,
    ) {}
}
