<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ShipDGHazmatV1\Dto;

use ShipStream\FedEx\Dto;

final class ShippingDocumentSpecification extends Dto
{
    protected static array $attributeMap = ['op900detail' => 'op900Detail'];

    /**
     * @param  ?GeneralAgencyAgreementDetail  $generalAgencyAgreementDetail  Use this object to specify details to generate general agency agreement detail.
     * @param  ?ReturnInstructionsDetail  $returnInstructionsDetail  Specifies the production of the return document (document characteristics and printing). This information will print on the Return Instructions returned in the transaction for the Printed Return Label.
     * @param  ?Op900detail  $op900detail  Use this object to specify details to generate the OP-900 document for hazardous material packages.
     * @param  ?string[]  $shippingDocumentTypes  Conditionally required in order to obtain shipping documents.
     *
     * Indicates the types of shipping documents requested by the shipper
     * @param  ?CertificateOfOriginDetail  $certificateOfOrigin  The instructions indicating how to print the Certificate of Origin ( e.g. whether or not to include the instructions, image type, etc ...)
     * @param  ?CommercialInvoiceDetail  $commercialInvoiceDetail  The instructions indicating how to print the Commercial Invoice( e.g. image type) Specifies characteristics of a shipping document to be produced.
     * @param  ?UsmcaCertificationOfOriginDetail  $usmcaCertificationOfOriginDetail  The instructions indicating how to print the USMCA Certification of Origin ( e.g. whether or not to include the instructions, image type, etc ...)
     * @param  ?UsmcaCommercialInvoiceCertificationOfOriginDetail  $usmcaCommercialInvoiceCertificationOfOriginDetail  The instructions indicating commercial invoice certification of origin.
     */
    public function __construct(
        public ?GeneralAgencyAgreementDetail $generalAgencyAgreementDetail = null,
        public ?ReturnInstructionsDetail $returnInstructionsDetail = null,
        public ?Op900detail $op900detail = null,
        public ?array $shippingDocumentTypes = null,
        public ?CertificateOfOriginDetail $certificateOfOrigin = null,
        public ?CommercialInvoiceDetail $commercialInvoiceDetail = null,
        public ?UsmcaCertificationOfOriginDetail $usmcaCertificationOfOriginDetail = null,
        public ?UsmcaCommercialInvoiceCertificationOfOriginDetail $usmcaCommercialInvoiceCertificationOfOriginDetail = null,
        public ?DangerousGoodsShippersDeclarationDetail $dangerousGoodsShippersDeclarationDetail = null,
    ) {}
}
