<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ShipDGHazmatV1\Dto;

use ShipStream\FedEx\Dto;

final class StringBarcode extends Dto
{
    /**
     * @param  ?string  $type  The kind of barcode data in this instance. example valid values are:<br>ADDRESS - Represents the recipient address<br>GROUND - FedEx Ground parcel barcode<br>Example: ADDRESS
     * @param  ?string  $value  The data content of this instance.<br>Example: 1010062512241535917900794953544894
     */
    public function __construct(
        public ?string $type = null,
        public ?string $value = null,
    ) {}
}
