<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ShipDGHazmatV1\Dto;

use ShipStream\FedEx\Dto;

final class TransactionDetailVo extends Dto
{
    /**
     * @param  ?string  $transactionDetails  Includes descriptive data that governs data payload language/translations. The TransactionDetail from the request is echoed back to the caller in the corresponding reply.Example: transactionDetails
     * @param  ?string  $transactionId  This element allows you to assign a unique identifier to your transaction. This element is returned in the reply and helps you match requests to replies.Maximum of 40 characters allowed.<br>Example: 12345
     */
    public function __construct(
        public ?string $transactionDetails = null,
        public ?string $transactionId = null,
    ) {}
}
