<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ShipDGHazmatV1\Dto;

use ShipStream\FedEx\Dto;

final class Weight extends Dto
{
    /**
     * @param  string  $units  Specifies the package weight unit type.
     * @param  float  $value  Weight Value.<br> Example: 68.25<br><a onclick='loadDocReference("packagetypes")'>Click here to see Weight values</a>
     */
    public function __construct(
        public string $units,
        public float $value,
    ) {}
}
