<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\TradeDocumentsUploadV1\Dto;

use ShipStream\FedEx\Dto;

final class Errors extends Dto
{
    protected static array $complexArrayTypes = ['parameterList' => ErrorsParameterList::class];

    /**
     * @param  ?string  $code  Indicates the error code.<br  >Example: 1001
     * @param  ?string  $message  Indicates the description of API error alert message.<br>Example: Invalid request: invalid input : destinationCountryCode is Required
     * @param  ErrorsParameterList[]|null  $parameterList  These are parameter details such as paramter with a key.
     */
    public function __construct(
        public ?string $code = null,
        public ?string $message = null,
        public ?array $parameterList = null,
    ) {}
}
