<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\TradeDocumentsUploadV1\Dto;

use ShipStream\FedEx\Dto;

final class MultiDocumentPreResponse extends Dto
{
    /**
     * @param  ?string  $fileReferenceId  Unique reference to the file
     */
    public function __construct(
        public ?string $fileReferenceId = null,
        public ?MultiMetaDataPreResponse $metaData = null,
    ) {}
}
