<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: ShipStream\FedEx\Generator\Generators\RequestGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\AccountRegistrationV1\Requests;

use Exception;
use Saloon\Contracts\Body\HasBody;
use Saloon\Enums\Method;
use Saloon\Http\Response;
use Saloon\Traits\Body\HasJsonBody;
use ShipStream\FedEx\Api\AccountRegistrationV1\Dto\CustomerKeyInputVo;
use ShipStream\FedEx\Api\AccountRegistrationV1\Responses\ErrorResponseVo;
use ShipStream\FedEx\Api\AccountRegistrationV1\Responses\IrcpResponseVo;
use ShipStream\FedEx\Request;

/**
 * Create Customer Key
 *
 * API End point being used to perform address validation during the credentials registration process
 * of csp consumers. This endpoint validates the address and generates the keys.<br><i>Note: FedEx APIs
 * do not support Cross-Origin Resource Sharing (CORS) mechanism.<i>
 */
class CreateCustomerKey extends Request implements HasBody
{
    use HasJsonBody;

    protected Method $method = Method::POST;

    /**
     * @param  CustomerKeyInputVo  $customerKeyInputVo  This is a request object for requesting customer key and secret key.
     */
    public function __construct(
        public CustomerKeyInputVo $customerKeyInputVo,
    ) {}

    public function resolveEndpoint(): string
    {
        return '/registration/v2/address/keysgeneration';
    }

    public function createDtoFromResponse(Response $response): IrcpResponseVo|ErrorResponseVo
    {
        $status = $response->status();
        $responseCls = match ($status) {
            200 => IrcpResponseVo::class,
            400, 401, 403, 404, 500, 429 => ErrorResponseVo::class,
            default => throw new Exception("Unhandled response status: {$status}")
        };

        return $responseCls::deserialize($response->json());
    }

    public function defaultBody(): array
    {
        return $this->customerKeyInputVo->toArray();
    }
}
