<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: Crescat\SaloonSdkGenerator\Generators\DtoGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\AddressValidationV1\Dto;

use ShipStream\FedEx\Dto;

final class AddressResolutionControlParameters extends Dto
{
    /**
     * @param  ?bool  $includeResolutionTokens  Use this to request detailed information of the address components once the validation is complete. The details specify the changes made to each address component to resolve the address.
     */
    public function __construct(
        public ?bool $includeResolutionTokens = null,
    ) {}
}
