<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: ShipStream\FedEx\Generator\Generators\RequestGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\ConsolidationV1\Requests;

use Exception;
use Saloon\Contracts\Body\HasBody;
use Saloon\Enums\Method;
use Saloon\Http\Response;
use Saloon\Traits\Body\HasJsonBody;
use ShipStream\FedEx\Api\ConsolidationV1\Dto\ConsolidationShipmentResultsInputVo;
use ShipStream\FedEx\Api\ConsolidationV1\Responses\ConsolidationShipmentResultsResponse;
use ShipStream\FedEx\Api\ConsolidationV1\Responses\ErrorResponseVo;
use ShipStream\FedEx\Api\ConsolidationV1\Responses\ErrorResponseVo2;
use ShipStream\FedEx\Request;

/**
 * ConsolidationShipmentResults
 *
 * This endpoint provides the ablity to find out if the asyncronous processing for open shipments is
 * complete.  If complete, the response returns the label buffers and any applicable documents.
 * <br>Operating Companies - FedEx Express, FedEx Ground
 */
class ConsolidationShipmentResults extends Request implements HasBody
{
    use HasJsonBody;

    protected Method $method = Method::POST;

    public function __construct(
        public ConsolidationShipmentResultsInputVo $consolidationShipmentResultsInputVo,
    ) {
    }

    public function resolveEndpoint(): string
    {
        return '/ship/v1/consolidations/results';
    }

    public function createDtoFromResponse(
        Response $response,
    ): ConsolidationShipmentResultsResponse|ErrorResponseVo|ErrorResponseVo2 {
        $status = $response->status();
        $responseCls = match ($status) {
            200 => ConsolidationShipmentResultsResponse::class,
            400, 500 => ErrorResponseVo::class,
            401, 403, 404, 503 => ErrorResponseVo2::class,
            default => throw new Exception("Unhandled response status: {$status}")
        };

        return $responseCls::deserialize($response->json());
    }

    public function defaultBody(): array
    {
        return $this->consolidationShipmentResultsInputVo->toArray();
    }
}
