<?php

/**
 * This file is auto-generated by Saloon SDK Generator
 * Generator: ShipStream\FedEx\Generator\Generators\ResourceGenerator
 * Do not modify it directly.
 */

declare(strict_types=1);

namespace ShipStream\FedEx\Api\LocationsSearchV1;

use Saloon\Http\Response;
use ShipStream\FedEx\Api\LocationsSearchV1\Dto\FullSchemaFindLocation;
use ShipStream\FedEx\Api\LocationsSearchV1\Requests\FindLocation;
use ShipStream\FedEx\BaseResource;

class Api extends BaseResource
{
    public function findLocation(FullSchemaFindLocation $fullSchemaFindLocation): Response
    {
        return $this->connector->send(new FindLocation($fullSchemaFindLocation));
    }
}
